<?php
return [
    'audio' => [
        'backend' => 'varchar',
        'frontend' => 'attr\file\frontend',
        'filter' => 'attr\text\frontend',
        'validator' => 'attr\file\validator',
        'viewer' => 'attr\audio\viewer',
        'ignorable' => true,
        'uploadable' => true,
        'accept' => [
            'audio/aac',
            'audio/flac',
            'audio/mp3',
            'audio/mpeg',
            'audio/mpeg3',
            'audio/ogg',
            'audio/wav',
            'audio/wave',
            'audio/webm',
            'audio/x-aac',
            'audio/x-flac',
            'audio/x-mp3',
            'audio/x-mpeg',
            'audio/x-mpeg3',
            'audio/x-pn-wav',
            'audio/x-wav',
        ],
    ],
    'block' => [
        'backend' => 'varchar',
        'frontend' => 'attr\select\frontend',
        'validator' => 'attr\opt\validator',
        'viewer' => 'attr\opt\viewer',
        'opt' => 'attr\block\opt',
    ],
    'bool' => [
        'backend' => 'bool',
        'frontend' => 'attr\bool\frontend',
        'filter' => 'attr\select\frontend',
        'viewer' => 'attr\opt\viewer',
        'opt' => 'attr\bool\opt',
    ],
    'date' => [
        'backend' => 'date',
        'frontend' => 'attr\date\frontend',
        'validator' => 'attr\date\validator',
        'viewer' => 'attr\date\viewer',
    ],
    'datetime' => [
        'backend' => 'datetime',
        'frontend' => 'attr\datetime\frontend',
        'filter' => 'attr\date\frontend',
        'validator' => 'attr\datetime\validator',
        'viewer' => 'attr\datetime\viewer',
    ],
    'decimal' => ['backend' => 'decimal', 'frontend' => 'attr\decimal\frontend'],
    'document' => [
        'backend' => 'varchar',
        'frontend' => 'attr\file\frontend',
        'filter' => 'attr\text\frontend',
        'validator' => 'attr\file\validator',
        'viewer' => 'attr\file\viewer',
        'ignorable' => true,
        'uploadable' => true,
        'accept' => [
            'application/msword',
            'application/pdf',
            'application/vnd.ms-excel',
            'application/vnd.ms-excel.sheet.macroEnabled.12',
            'application/vnd.oasis.opendocument.spreadsheet',
            'application/vnd.oasis.opendocument.text',
            'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
            'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
            'application/zip',
            'text/csv',
        ],
    ],
    'editor' => [
        'backend' => 'text',
        'frontend' => 'attr\textarea\frontend',
        'filter' => 'attr\text\frontend',
        'validator' => 'attr\editor\validator',
        'viewer' => 'attr\editor\viewer',
    ],
    'email' => [
        'backend' => 'varchar',
        'frontend' => 'attr\email\frontend',
        'validator' => 'attr\email\validator',
        'viewer' => 'attr\email\viewer',
    ],
    'entity' => [
        'backend' => 'int',
        'frontend' => 'attr\select\frontend',
        'validator' => 'attr\entity\validator',
        'viewer' => 'attr\entity\viewer',
        'opt' => 'attr\entity\opt',
    ],
    'entity_id' => [
        'backend' => 'varchar',
        'frontend' => 'attr\select\frontend',
        'validator' => 'attr\opt\validator',
        'viewer' => 'attr\opt\viewer',
        'opt' => 'attr\entity_id\opt',
        'max' => 50,
    ],
    'file' => [
        'backend' => 'varchar',
        'frontend' => 'attr\file\frontend',
        'filter' => 'attr\text\frontend',
        'validator' => 'attr\file\validator',
        'viewer' => 'attr\file\viewer',
        'ignorable' => true,
        'uploadable' => true,
    ],
    'iframe' => [
        'backend' => 'varchar',
        'frontend' => 'attr\url\frontend',
        'validator' => 'attr\url\validator',
        'viewer' => 'attr\iframe\viewer',
    ],
    'image' => [
        'backend' => 'varchar',
        'frontend' => 'attr\file\frontend',
        'filter' => 'attr\text\frontend',
        'validator' => 'attr\file\validator',
        'viewer' => 'attr\image\viewer',
        'ignorable' => true,
        'uploadable' => true,
        'accept' => ['image/gif', 'image/jpeg', 'image/png', 'image/svg+xml', 'image/webp'],
    ],
    'int' => ['backend' => 'int', 'frontend' => 'attr\int\frontend'],
    'json' => [
        'backend' => 'json',
        'frontend' => 'attr\json\frontend',
        'filter' => 'attr\text\frontend',
        'viewer' => 'attr\json\viewer',
    ],
    'multientity' => [
        'backend' => 'multiint',
        'frontend' => 'attr\select\frontend',
        'validator' => 'attr\multientity\validator',
        'viewer' => 'attr\multientity\viewer',
        'opt' => 'attr\entity\opt',
    ],
    'multiint' => [
        'backend' => 'multiint',
        'frontend' => 'attr\checkbox\frontend',
        'filter' => 'attr\select\frontend',
        'validator' => 'attr\opt\validator',
        'viewer' => 'attr\opt\viewer',
    ],
    'multitext' => [
        'backend' => 'multitext',
        'frontend' => 'attr\checkbox\frontend',
        'filter' => 'attr\select\frontend',
        'validator' => 'attr\opt\validator',
        'viewer' => 'attr\opt\viewer',
    ],
    'password' => [
        'backend' => 'varchar',
        'frontend' => 'attr\password\frontend',
        'ignorable' => true,
        'autocomplete' => 'new-password',
    ],
    'position' => [
        'backend' => 'varchar',
        'frontend' => 'attr\text\frontend',
        'validator' => 'attr\text\validator',
        'viewer' => 'attr\position\viewer',
        'auto' => true,
        'max' => 255,
    ],
    'privilege' => [
        'backend' => 'multitext',
        'frontend' => 'attr\checkbox\frontend',
        'filter' => 'attr\select\frontend',
        'validator' => 'attr\opt\validator',
        'viewer' => 'attr\opt\viewer',
        'opt' => 'attr\privilege\opt',
    ],
    'radio' => [
        'backend' => 'varchar',
        'frontend' => 'attr\radio\frontend',
        'filter' => 'attr\select\frontend',
        'validator' => 'attr\opt\validator',
        'viewer' => 'attr\opt\viewer',
    ],
    'range' => ['backend' => 'int', 'frontend' => 'attr\range\frontend'],
    'select' => [
        'backend' => 'varchar',
        'frontend' => 'attr\select\frontend',
        'validator' => 'attr\opt\validator',
        'viewer' => 'attr\opt\viewer',
    ],
    'serial' => ['backend' => 'serial', 'frontend' => 'attr\int\frontend', 'auto' => true],
    'tel' => [
        'backend' => 'varchar',
        'frontend' => 'attr\tel\frontend',
        'validator' => 'attr\text\validator',
        'viewer' => 'attr\tel\viewer',
    ],
    'text' => ['backend' => 'varchar', 'frontend' => 'attr\text\frontend', 'validator' => 'attr\text\validator'],
    'textarea' => [
        'backend' => 'text',
        'frontend' => 'attr\textarea\frontend',
        'filter' => 'attr\text\frontend',
        'validator' => 'attr\text\validator',
    ],
    'time' => [
        'backend' => 'time',
        'frontend' => 'attr\time\frontend',
        'validator' => 'attr\time\validator',
        'viewer' => 'attr\time\viewer',
    ],
    'uid' => ['backend' => 'varchar', 'frontend' => 'attr\text\frontend', 'validator' => 'attr\uid\validator'],
    'url' => [
        'backend' => 'varchar',
        'frontend' => 'attr\url\frontend',
        'validator' => 'attr\url\validator',
        'viewer' => 'attr\url\viewer',
    ],
    'urlpath' => [
        'backend' => 'varchar',
        'frontend' => 'attr\text\frontend',
        'validator' => 'attr\urlpath\validator',
        'viewer' => 'attr\url\viewer',
    ],
    'video' => [
        'backend' => 'varchar',
        'frontend' => 'attr\file\frontend',
        'filter' => 'attr\text\frontend',
        'validator' => 'attr\file\validator',
        'viewer' => 'attr\video\viewer',
        'ignorable' => true,
        'uploadable' => true,
        'accept' => ['video/mp4', 'video/ogg', 'video/webm'],
    ],
];
