<?php
return [
    'data:account' => ['event\account\data' => 100],
    'data:app' => ['event\app\data' => 100],
    'data:layout' => ['event\layout\data' => 100],
    'data:request' => ['event\request\data' => 100],
    'entity:postdelete:id:file' => ['event\file\postdelete' => 100],
    'entity:postsave:id:file' => ['event\file\postsave' => 100],
    'entity:postvalidate' => ['event\password\postvalidate' => 100, 'event\unique\postvalidate' => 200],
    'entity:postvalidate:id:page' => ['event\page\postvalidate_menu' => 100, 'event\page\postvalidate_url' => 200],
    'entity:predelete:id:role' => ['event\role\predelete' => 100],
    'entity:presave:id:page' => ['event\page\presave' => 100],
    'entity:prevalidate:id:file' => ['event\file\prevalidate' => 100],
    'layout:postrender:id:body' => ['event\filter\body' => 100],
    'response:html' => ['event\response\html' => 100],
    'response:html:account:logout' => ['event\response\html_account_logout' => 100],
    'response:html:block:api' => ['event\response\html_block_api' => 100],
    'response:html:delete' => ['event\response\html_delete' => 100],
    'response:json' => ['event\response\json' => 100],
];
