<?php
return [
    'aac' => 'audio',
    'csv' => 'file',
    'doc' => 'file',
    'docx' => 'file',
    'flac' => 'audio',
    'gif' => 'image',
    'gz' => 'file',
    'jpg' => 'image',
    'mp3' => 'audio',
    'mp4' => 'video',
    'odp' => 'file',
    'ods' => 'file',
    'odt' => 'file',
    'oga' => 'audio',
    'ogg' => 'audio',
    'ogv' => 'video',
    'pdf' => 'file',
    'png' => 'image',
    'ppt' => 'file',
    'pptx' => 'file',
    'rar' => 'file',
    'svg' => 'image',
    'tar' => 'file',
    'wav' => 'audio',
    'weba' => 'audio',
    'webm' => 'video',
    'webp' => 'image',
    'xls' => 'file',
    'xlsx' => 'file',
    'zip' => 'file',
];
