<?php
return [
    'dashboard' => [
        'name' => 'Dashboard',
        'url' => '/account/dashboard',
        'priv' => 'account/dashboard',
        'sort' => 10,
    ],
    'page' => [
        'name' => 'Pages',
        'sort' => 20,
    ],
    'page_content' => [
        'name' => 'Content Pages',
        'url' => '/page_content/admin',
        'priv' => 'page_content/admin',
        'parent_id' => 'page',
        'sort' => 10,
    ],
    'page_article' => [
        'name' => 'Articles',
        'url' => '/page_article/admin',
        'priv' => 'page_article/admin',
        'parent_id' => 'page',
        'sort' => 20,
    ],
    'layout' => [
        'name' => 'Layout',
        'url' => '/layout/admin',
        'priv' => 'layout/admin',
        'sort' => 30,
    ],
    'block' => [
        'name' => 'Blocks',
        'sort' => 40,
    ],
    'block_content' => [
        'name' => 'Content Blocks',
        'url' => '/block_content/admin',
        'priv' => 'block_content/admin',
        'parent_id' => 'block',
        'sort' => 10,
    ],
    'block_teaser' => [
        'name' => 'Teaser Blocks',
        'url' => '/block_teaser/admin',
        'priv' => 'block_teaser/admin',
        'parent_id' => 'block',
        'sort' => 20,
    ],
    'file' => [
        'name' => 'Files',
        'sort' => 50,
    ],
    'file_image' => [
        'name' => 'Images',
        'url' => '/file_image/admin',
        'priv' => 'file_image/admin',
        'parent_id' => 'file',
        'sort' => 10,
    ],
    'file_doc' => [
        'name' => 'Documents',
        'url' => '/file_doc/admin',
        'priv' => 'file_doc/admin',
        'parent_id' => 'file',
        'sort' => 20,
    ],
    'file_video' => [
        'name' => 'Videos',
        'url' => '/file_video/admin',
        'priv' => 'file_video/admin',
        'parent_id' => 'file',
        'sort' => 30,
    ],
    'file_audio' => [
        'name' => 'Audios',
        'url' => '/file_audio/admin',
        'priv' => 'file_audio/admin',
        'parent_id' => 'file',
        'sort' => 40,
    ],
    'role' => [
        'name' => 'Roles',
        'url' => '/role/admin',
        'priv' => 'role/admin',
        'sort' => 60,
    ],
    'account' => [
        'name' => 'Accounts',
        'url' => '/account/admin',
        'priv' => 'account/admin',
        'sort' => 70,
    ],
    'home' => [
        'name' => 'Homepage',
        'url' => '/',
        'priv' => 'page_content/view',
        'sort' => 80,
    ],
    'profile' => [
        'name' => 'Profile',
        'url' => '/account/profile',
        'priv' => 'account/profile',
        'sort' => 90,
    ],
    'logout' => [
        'name' => 'Logout',
        'url' => '/account/logout',
        'priv' => 'account/logout',
        'sort' => 100,
    ],
];
