<?php
return [
    'audio' => ['call' => 'viewer\audio'],
    'date' => ['call' => 'viewer\date'],
    'datetime' => ['call' => 'viewer\datetime'],
    'email' => ['call' => 'viewer\email'],
    'enc' => ['call' => 'viewer\enc'],
    'entity' => ['call' => 'viewer\entity'],
    'file' => ['call' => 'viewer\file'],
    'iframe' => ['call' => 'viewer\iframe'],
    'image' => ['call' => 'viewer\image'],
    'json' => ['call' => 'viewer\json'],
    'multientity' => ['call' => 'viewer\multientity'],
    'opt' => ['call' => 'viewer\opt'],
    'position' => ['call' => 'viewer\position'],
    'raw' => ['call' => 'viewer\raw'],
    'tel' => ['call' => 'viewer\tel'],
    'time' => ['call' => 'viewer\time'],
    'url' => ['call' => 'viewer\url'],
    'video' => ['call' => 'viewer\video'],
];
