<?php namespace cms; /** @var callable $§ */?>
<meta charset="<?= cfg('app', 'charset');?>" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
<title><?=$§('title');?></title>
<link rel="stylesheet" href="<?=url_theme('theme.css');?>" />
<?php if (account_user()):?>
<script src="<?=url_theme('ckeditor/ckeditor.js');?>"></script>
<script src="<?=url_theme('theme.js');?>"></script>
<script>
    const app =
    {
        i18n: <?=json_encode(cfg('i18n'));?>,
        _: function (key)
        {
            return this.i18n[key] ? this.i18n[key] : key;
        }
    };
</script>
<?php endif;?>
