<?php
namespace app;
use function account\user;
/** @var callable $§ */
?>
<meta charset="<?= cfg('app', 'charset');?>" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
<title><?=$§('title');?></title>
<link rel="stylesheet" href="<?= theme('theme.css');?>" />
<?php if (user()):?>
<script src="<?= theme('ckeditor/ckeditor.js');?>"></script>
<script src="<?= theme('theme.js');?>"></script>
<script>
    const app =
    {
        cfg:
        {
            i18n: <?=json_encode(cfg('i18n'));?>
        },
        i18n: function (key)
        {
            return this.cfg.i18n[key] ? this.cfg.i18n[key] : key;
        }
    };
</script>
<?php endif;?>
