<?php
namespace app;
use function http\req;
use function layout\§;
/** @var callable $§ */
?>
<!doctype html>
<html data-path="<?= req('path');?>">
    <head>
        <?= §('head');?>
    </head>
    <body>
        <?= §('top');?>
        <?= §('msg');?>
        <main>
            <?= §('left');?>
            <?= §('main');?>
            <?= §('right');?>
        </main>
        <?= §('bottom');?>
    </body>
</html>
