<?php
namespace app;
/** @var callable $§ */
?>
<!doctype html>
<html lang="<?=data('lang');?>" data-area="<?=data('area');?>" data-ent="<?=data('ent');?>" data-act="<?=data('act');?>"<?php if (data('id')):?>  data-id="<?=data('id');?>"<?php endif;?>>
    <head>
        <?=§('head');?>
    </head>
    <body>
        <?=§('top');?>
        <?=§('msg');?>
        <main>
            <?=§('main');?>
            <?=§('sidebar');?>
        </main>
        <?=§('bottom');?>
    </body>
</html>
