<?php
namespace app;
use http;
use layout;
/** @var callable $§ */
?>
<!doctype html>
<html data-path="<?= http\req('path');?>">
    <head>
        <?= layout\§('head');?>
    </head>
    <body>
        <?= layout\§('top');?>
        <?= layout\§('msg');?>
        <main>
            <?= layout\§('left');?>
            <?= layout\§('main');?>
            <?= layout\§('right');?>
        </main>
        <?= layout\§('bottom');?>
    </body>
</html>
