version: "3.8"
volumes:
  db: {}
  file: {}
services:
  db:
    image: akilli/postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - db:/data
      - file:/app
      - ./db:/init/postgres
  php:
    image: akilli/php
    depends_on:
      - db
    restart: unless-stopped
    environment:
      - DEV=1
    volumes:
      - file:/data/file:nocopy
      - .:/app
  www:
    image: akilli/nginx
    depends_on:
      - db
      - php
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - file:/data/file:nocopy
      - .:/app
