version: "3.2"
volumes:
  app:
    driver_opts:
      type: none
      device: /docker/app
      o: bind
  nginx:
    driver_opts:
      type: none
      device: /docker/nginx
      o: bind
  postgres: {}
  ssl:
    driver_opts:
      type: none
      device: /docker/ssl
      o: bind
