version: "3.3"
networks:
  default:
    external:
      name: proxy
volumes:
  app: {}
  data: {}
  db: {}
services:
  cms:
    image: akilli/nginx
    container_name: cms
    depends_on:
      - cms-app
      - cms-data
    restart: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "HostRegexp: {domain:.+}"
      traefik.frontend.priority: "1"
      traefik.port: "80"
    volumes:
      - source: app
        target: /app
        type: volume
        volume:
          nocopy: true
      - source: data
        target: /data
        type: volume
        volume:
          nocopy: true
  cms-app:
    image: registry.ayhan.biz/cms
    container_name: cms-app
    depends_on:
      - cms-data
    restart: unless-stopped
    volumes:
      - source: app
        target: /app
        type: volume
      - source: data
        target: /data
        type: volume
        volume:
          nocopy: true
  cms-data:
    image: registry.ayhan.biz/cms-data
    container_name: cms-data
    restart: unless-stopped
    volumes:
      - source: data
        target: /app
        type: volume
      - source: db
        target: /data
        type: volume
