version: "3.5"
networks:
  proxy:
    external: true
volumes:
  app: {}
  db: {}
  file: {}
  tmp: {}
services:
  db:
    image: akilli/postgres
    restart: unless-stopped
    networks:
      default: {}
      proxy:
        aliases:
          - cms-db
    volumes:
      - source: db
        target: /data
        type: volume
      - source: file
        target: /app
        type: volume
  php:
    image: akilli/cms
    depends_on:
      - db
    restart: unless-stopped
    networks:
      default: {}
      proxy:
        aliases:
          - cms-php
    volumes:
      - source: app
        target: /app
        type: volume
      - source: file
        target: /data/file
        type: volume
        volume:
          nocopy: true
      - source: tmp
        target: /tmp
        type: volume
  www:
    image: akilli/nginx
    depends_on:
      - db
      - php
    restart: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.port: "80"
      traefik.frontend.rule: "Host: cms.app.loc"
      traefik.docker.network: "proxy"
    networks:
      default: {}
      proxy:
        aliases:
          - cms
          - cms.app.loc
    volumes:
      - source: app
        target: /app
        type: volume
        volume:
          nocopy: true
      - source: file
        target: /data/file
        type: volume
        volume:
          nocopy: true
