version: "3.8"
volumes:
  app:
    driver_opts:
      type: none
      device: ${PWD}
      o: bind,uid=1000,gid=1000
  db: {}
  file: {}
  opt: {}
  php: {}
  www: {}
services:
  db:
    image: akilli/postgres
    restart: unless-stopped
    volumes:
      - db:/data
      - file:/app
      - ./db:/init/postgres
  php:
    image: akilli/php
    depends_on:
      - db
    restart: unless-stopped
    volumes:
      - app:/app
      - file:/data/file:nocopy
      - opt:/opt
      - php:/tmp
      - ./php.dev.ini:/etc/php/conf.d/zzz.ini
  www:
    image: akilli/nginx
    depends_on:
      - db
      - php
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - app:/app:nocopy
      - file:/data/file:nocopy
      - opt:/opt:nocopy
      - www:/tmp
