version: "3.2"
networks:
  admin_default:
    external: true
volumes:
  postgres: {}
services:
  qnd:
    image: akilli/nginx
    container_name: qnd
    restart: unless-stopped
    labels:
      traefik.port: "80"
      traefik.docker.network: "admin_default"
    networks:
      - default
      - admin_default
    volumes:
      - source: .
        target: /app
        type: bind
        read_only: true
      - source: ./nginx.conf
        target: /etc/nginx/sites-enabled/default.conf
        type: bind
        read_only: true
  php:
    image: akilli/php
    container_name: qnd-php
    restart: unless-stopped
    volumes:
      - source: .
        target: /app
        type: bind
  postgres:
    image: akilli/postgres
    container_name: qnd-postgres
    restart: unless-stopped
    volumes:
      - source: postgres
        target: /var/lib/postgresql
        type: volume

