version: "3.2"
networks:
  default:
    external:
      name: eqmh
volumes:
  app: {}
  data: {}
  db: {}
services:
  qnd:
    image: akilli/nginx
    container_name: qnd
    restart: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "HostRegexp: {domain:.+}"
      traefik.frontend.priority: "1"
      traefik.port: "80"
    volumes:
      - source: app
        target: /app
        type: volume
        volume:
          nocopy: true
      - source: data
        target: /data
        type: volume
        volume:
          nocopy: true
  qnd-app:
    image: registry.test.eqmh.de/qnd
    container_name: qnd-app
    restart: unless-stopped
    network_mode: "service:qnd"
    volumes:
      - source: app
        target: /app
        type: volume
      - source: data
        target: /data
        type: volume
        volume:
          nocopy: true
  qnd-data:
    image: registry.test.eqmh.de/qnd-data
    container_name: qnd-data
    restart: unless-stopped
    volumes:
      - source: data
        target: /app
        type: volume
      - source: db
        target: /data
        type: volume
