version: "3.8"
volumes:
  app: {}
  db: {}
  file: {}
  opt: {}
  php: {}
  www: {}
services:
  db:
    image: akilli/cms-db
    restart: unless-stopped
    volumes:
      - db:/data
      - file:/app
  php:
    image: akilli/cms
    depends_on:
      - db
    restart: unless-stopped
    volumes:
      - app:/app
      - file:/data/file:nocopy
      - opt:/opt
      - php:/tmp
  www:
    image: akilli/nginx
    depends_on:
      - db
      - php
    restart: unless-stopped
    volumes:
      - app:/app:nocopy
      - file:/data/file:nocopy
      - opt:/opt:nocopy
      - www:/tmp
