version: '3'
volumes:
    postgres-data: {}
services:
    postgres:
        image: akilli/postgres
        restart: unless-stopped
        volumes:
            - postgres-data:/var/lib/postgresql
    php:
        image: akilli/php
        restart: unless-stopped
        volumes:
            - .:/app
    nginx:
        image: akilli/nginx
        depends_on:
            - php
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx.conf:/etc/nginx/sites-available/default.conf
            - .:/app
