version: "3.2"
volumes:
  app:
    driver_opts:
      type: none
      device: ${PWD}/..
      o: bind,uid=1000,gid=1000
  nginx:
    driver_opts:
      type: none
      device: ${PWD}/nginx/loc
      o: bind,uid=1000,gid=1000
  postgres: {}
  ssl:
    driver_opts:
      type: none
      device: ${PWD}/../../ssl/loc
      o: bind,uid=1000,gid=1000
services:
  nginx:
    image: akilli/nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - app:/app:ro
      - nginx:/etc/nginx/sites-enabled:ro
      - ssl:/etc/nginx/ssl:ro
  php:
    image: akilli/php
    container_name: php
    restart: unless-stopped
    volumes:
      - app:/app
  postgres:
    image: akilli/postgres
    container_name: postgres
    restart: unless-stopped
    volumes:
      - postgres:/var/lib/postgresql
