version: "3.7"
networks:
  default:
    external:
      name: proxy
  intern: {}
volumes:
  app: {}
  db: {}
  file: {}
  tmp: {}
services:
  cms-db:
    image: akilli/postgres
    restart: unless-stopped
    networks:
      default: {}
      intern:
        aliases:
          - db
    volumes:
      - source: db
        target: /data
        type: volume
      - source: file
        target: /app
        type: volume
  cms-php:
    image: akilli/cms
    depends_on:
      - cms-db
    restart: unless-stopped
    networks:
      default: {}
      intern:
        aliases:
          - php
    volumes:
      - source: app
        target: /app
        type: volume
      - source: file
        target: /data/file
        type: volume
        volume:
          nocopy: true
      - source: tmp
        target: /tmp
        type: volume
  cms-www:
    image: akilli/nginx
    depends_on:
      - cms-db
      - cms-php
    restart: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.port: "80"
      traefik.frontend.rule: "Host: cms.app.loc"
      traefik.docker.network: "proxy"
    networks:
      default: {}
      intern:
        aliases:
          - www
    volumes:
      - source: app
        target: /app
        type: volume
        volume:
          nocopy: true
      - source: file
        target: /data/file
        type: volume
        volume:
          nocopy: true
