version: "3.2"
networks:
  eqmh:
    external: true
volumes:
  app: {}
  data: {}
  db: {}
services:
  app:
    image: akilli/qnd
    container_name: qnd-app
    restart: unless-stopped
    depends_on:
      - data
    volumes:
      - source: app
        target: /app
        type: volume
      - source: data
        target: /data
        type: volume
        volume:
          nocopy: true
  data:
    image: akilli/qnd-data
    container_name: qnd-data
    restart: unless-stopped
    volumes:
      - source: data
        target: /app
        type: volume
      - source: db
        target: /data
        type: volume
  qnd:
    image: akilli/nginx
    container_name: test.eqmh.de
    restart: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "HostRegexp: test.eqmh.de, {subdomain:[a-z0-9_-]+}.test.eqmh.de"
      traefik.frontend.priority: 1
      traefik.port: "80"
      traefik.docker.network: "admin_default"
    networks:
      - default
      - eqmh
    depends_on:
      - app
      - data
    volumes:
      - source: app
        target: /app
        type: volume
        read_only: true
      - source: data
        target: /data
        type: volume
        read_only: true
