version: '3'
volumes:
    postgres-data: {}
services:
    app:
        image: akilli/base
        volumes:
            - .:/app
    postgres:
        image: akilli/postgres
        ports:
            - "5432:5432"
        volumes:
            - postgres-data:/var/lib/postgresql
    php:
        image: akilli/php
        ports:
            - "9000:9000"
        volumes_from:
            - app
    nginx:
        image: akilli/nginx
        depends_on:
            - php
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx/default.conf:/etc/nginx/sites-available/default.conf
        volumes_from:
            - app
