version: "3.2"
networks:
  admin_default:
    external: true
volumes:
  app: {}
  data: {}
  db: {}
services:
  app:
    image: akilli/qnd
    container_name: qnd.app
    restart: unless-stopped
    depends_on:
      - data
    volumes:
      - source: app
        target: /app
        type: volume
      - source: data
        target: /data
        type: volume
        volume:
          nocopy: true
  data:
    image: akilli/qnd-data
    container_name: qnd.data
    restart: unless-stopped
    volumes:
      - source: data
        target: /app
        type: volume
      - source: db
        target: /data
        type: volume
  qnd:
    image: akilli/nginx
    container_name: qnd
    restart: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.port: "80"
      traefik.docker.network: "admin_default"
    networks:
      - admin_default
      - default
    depends_on:
      - app
      - data
    volumes:
      - source: app
        target: /app
        type: volume
        read_only: true
      - source: data
        target: /data
        type: volume
        read_only: true
