<?php
namespace app;
/** @var callable $var */
?>
<link rel="stylesheet" href="<?=gui('base.css');?>" />
<link rel="stylesheet" href="<?=gui('nav.css');?>" />
<link rel="stylesheet" href="<?=gui('form.css');?>" />
<link rel="stylesheet" href="<?=gui('admin.css');?>" />
<script src="<?=gui('polyfill/datetime.js');?>"></script>
<script src="<?=gui('app.js');?>"></script>
<script src="<?=gui('delete.js');?>"></script>
<script src="<?=gui('password.js');?>"></script>
<script src="<?=gui('multicheckbox.js');?>"></script>
<script src="<?=gui('toggle.js');?>"></script>
<script src="<?=gui('ckeditor/ckeditor.js');?>"></script>
<script src="<?=gui('browser.js');?>"></script>
<script src="<?=gui('rte.js');?>"></script>
<script src="<?=gui('print.js');?>"></script>
