<?php
namespace app;
/** @var callable $var */
?>
<link rel="stylesheet" href="<?=gui('base.css');?>" />
<link rel="stylesheet" href="<?=gui('admin.css');?>" />
<script src="<?=gui('app.js');?>"></script>
<script src="<?=gui('multicheckbox.js');?>"></script>
<script src="<?=gui('toggle.js');?>"></script>
<script src="<?=gui('polyfill/datetime.js');?>"></script>
<script src="<?=gui('ckeditor/ckeditor.js');?>"></script>
<script src="<?=gui('admin.js');?>"></script>
<script src="<?=gui('print.js');?>"></script>
