<?php
namespace app;
/** @var callable $block */
?>
<link rel="stylesheet" href="<?=gui('base.css');?>" />
<link rel="stylesheet" href="<?=gui('details.css');?>" />
<link rel="stylesheet" href="<?=gui('flickity.css');?>" />
<link rel="stylesheet" href="<?=gui('flickity-fullscreen.css');?>" />
<link rel="stylesheet" href="<?=gui('app.css');?>" />
<script src="<?=gui('app.js');?>"></script>
<script src="<?=gui('details.js');?>"></script>
<script src="<?=gui('toggle.js');?>"></script>
<script src="<?=gui('flickity.js');?>"></script>
<script src="<?=gui('flickity-fullscreen.js');?>"></script>
<script src="<?=gui('slider.js');?>"></script>
<script src="<?=gui('datetime.js');?>"></script>
<script src="<?=gui('multicheckbox.js');?>"></script>
<script src="<?=gui('links.js');?>"></script>
<script src="<?=gui('print.js');?>"></script>
