<?php
namespace app;
/** @var callable $block */
?>
<link rel="stylesheet" href="<?=gui('base.css');?>" />
<link rel="stylesheet" href="<?=gui('details.css');?>" />
<link rel="stylesheet" href="<?=gui('flickity.css');?>" />
<link rel="stylesheet" href="<?=gui('app.css');?>" />
<script src="<?=gui('app.js');?>"></script>
<script src="<?=gui('details.js');?>"></script>
<script src="<?=gui('flickity.js');?>"></script>
<script src="<?=gui('app-all.js');?>"></script>
<script src="<?=gui('app-print.js');?>"></script>
