<?php
namespace app;
/** @var callable $var */
?>
<link rel="stylesheet" href="<?=gui('base.css');?>" />
<link rel="stylesheet" href="<?=gui('font.css');?>" />
<link rel="stylesheet" href="<?=gui('polyfill/details.css');?>" />
<link rel="stylesheet" href="<?=gui('slider/flickity.css');?>" />
<link rel="stylesheet" href="<?=gui('slider/slider.css');?>" />
<link rel="stylesheet" href="<?=gui('nav.css');?>" />
<link rel="stylesheet" href="<?=gui('table.css');?>" />
<link rel="stylesheet" href="<?=gui('form.css');?>" />
<link rel="stylesheet" href="<?=gui('public.css');?>" />
<script src="<?=gui('polyfill/details.js');?>"></script>
<script src="<?=gui('polyfill/datetime.js');?>"></script>
<script src="<?=gui('app.js');?>"></script>
<script src="<?=gui('multicheckbox.js');?>"></script>
<script src="<?=gui('toggle.js');?>"></script>
<script src="<?=gui('slider/flickity.js');?>"></script>
<script src="<?=gui('slider/slider.js');?>"></script>
<script src="<?=gui('print.js');?>"></script>
