<?php
namespace app;
/** @var callable $var */
?>
<link rel="stylesheet" href="<?=gui('base.css');?>" />
<link rel="stylesheet" href="<?=gui('polyfill/details.css');?>" />
<link rel="stylesheet" href="<?=gui('flickity/flickity.css');?>" />
<link rel="stylesheet" href="<?=gui('public.css');?>" />
<script src="<?=gui('polyfill/details.js');?>"></script>
<script src="<?=gui('polyfill/datetime.js');?>"></script>
<script src="<?=gui('app.js');?>"></script>
<script src="<?=gui('multicheckbox.js');?>"></script>
<script src="<?=gui('toggle.js');?>"></script>
<script src="<?=gui('flickity/flickity.js');?>"></script>
<script src="<?=gui('slider.js');?>"></script>
<script src="<?=gui('print.js');?>"></script>
