<?php
namespace app;
use attr;
use session;
/** @var callable $§ */
?>
<section id="<?=$§('id');?>" class="index">
    <h1><?=$§('title');?></h1>
    <?php if (allowed('*/edit')):?>
    <p class="create"><a href="<?=url('*/edit');?>" role="button" class="icon" title="<?=i18n('New Entry');?>">add_circle</a></p>
    <?php endif;?>
    <?php if ($§('data')):?>
    <form method="post" class="search">
        <input type="search" name="param[q]" value="<?=$§('param')['q'] ?? '';?>" placeholder="<?=i18n('Search Term');?>" />
        <input type="submit" value="search" title="<?=i18n('Search');?>" class="icon" />
        <input type="hidden" name="token" value="<?=session\token();?>" />
    </form>
    <?php $p = $§('param') + ['sort' => null, 'dir' => null];?>
    <table class="data">
        <thead>
            <tr>
                <?php foreach ($§('attr') as $attr):?>
                    <?php $dir = $p['sort'] === $attr['id'] && $p['dir'] === 'asc' ? 'desc' : 'asc'; ?>
                <th>
                    <a href="<?=url('*/*', ['sort' => $attr['id'], 'dir' => $dir] + $p);?>"><?=$attr['name'];?></a>
                    <?php if ($p['sort'] === $attr['id']):?>
                    <span class="icon"><?=$p['dir'] === 'asc' ? 'arrow_drop_up' : 'arrow_drop_down';?></span>
                    <?php endif;?>
                </th>
                <?php endforeach;?>
                <th>
                    <?=i18n('Actions');?>
                </th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($§('data') as $data):?>
            <tr>
                <?php foreach ($§('attr') as $attr):?>
                <td>
                    <?=attr\viewer($attr, $data);?>
                </td>
                <?php endforeach;?>
                <td>
                    <?php if (allowed('*/view')):?>
                    <a href="<?=$data['url'] ?? url('*/view/' . $data['id']);?>" class="icon" title="<?=i18n('View');?>">visibility</a>
                    <?php endif;?>
                    <?php if (allowed('*/edit')):?>
                    <a href="<?=url('*/edit/' . $data['id']);?>" class="icon" title="<?=i18n('Edit');?>">edit</a>
                    <?php endif;?>
                    <?php if (allowed('*/delete')):?>
                    <a href="<?=url('*/delete/' . $data['id']);?>" class="delete icon" title="<?=i18n('Delete');?>">delete</a>
                    <?php endif;?>
                </td>
            </tr>
            <?php endforeach;?>
        </tbody>
    </table>
    <nav class="pager">
        <div class="info">
            <?=i18n('%s to %s of %s', $§('min'), $§('max'), $§('size'));?>
        </div>
        <div class="links">
            <?php foreach ($§('pager') as $link):?>
                <?php if (!empty($link['active'])):?>
            <span><?=$link['name'];?></span>
                <?php else:?>
            <a href="<?=url('*/*', $link['param']);?>"><?=$link['name'];?></a>
                <?php endif;?>
            <?php endforeach;?>
        </div>
    </nav>
    <?php else:?>
    <p><?=i18n('No entries found');?></p>
    <?php endif;?>
</section>
