<?php
namespace app;
use function account\allowed;
use function attr\editor;
use function session\token;
/** @var callable $§ */
?>
<?php if ($data = $§('data')):?>
<section id="<?=$§('id');?>">
    <h1><?=$§('title');?></h1>
    <form method="post" enctype="multipart/form-data">
        <fieldset>
            <legend><?=$data['name'] ?? _('New Entry');?></legend>
            <?php foreach ($§('attr') as $attr):?>
                <?php if (!$html = editor($attr, $data)) continue;?>
            <div data-attr="<?=$attr['id'];?>">
                <?=$html;?>
            </div>
            <?php endforeach;?>
        </fieldset>
        <?php if (allowed('*/admin')):?>
        <a role="button" href="<?= url('*/admin');?>"><?= _('Back');?></a>
        <?php endif;?>
        <input type="submit" value="<?= _('Save');?>" />
        <input type="hidden" name="token" value="<?= token();?>" />
    </form>
</section>
<?php endif;?>
