<?php
namespace app;
use attr;
/** @var callable $§ */
?>
<section id="<?=$§('id');?>">
    <?php if ($§('title')):?>
    <h1><?=$§('title');?></h1>
    <?php endif;?>
    <form method="post"<?php if (in_array('file', array_column($§('attr'), 'type'))):?> enctype="multipart/form-data"<?php endif;?>>
        <fieldset>
            <?php foreach ($§('attr') as $attr):?>
            <div data-attr="<?=$attr['id'];?>" data-type="<?=$attr['type'];?>">
                <?=attr\frontend($attr, $§('data'));?>
            </div>
            <?php endforeach;?>
        </fieldset>
        <?php if (allowed($§('ent')['id'] . '/admin')):?>
        <a role="button" href="<?=url($§('ent')['id'] . '/admin');?>"><?=i18n('Back');?></a>
        <?php endif;?>
        <input type="submit" value="<?=i18n('Submit');?>" />
        <input type="hidden" name="token" value="<?=$§('token');?>" />
    </form>
</section>
