<?php
namespace app;
use function file\accept;
use function session\token;
/** @var callable $§ */
?>
<form id="<?=$§('id');?>" action="<?= url('*/import');?>" method="post" enctype="multipart/form-data">
    <h1><?= i18n('Import');?></h1>
    <p><?= i18n('Import one or multiple files');?></p>
    <input type="file" name="data[import][]" required="required" multiple="multiple" accept="<?= accept('file');?>" />
    <input type="submit" value="file_upload" class="icon" title="<?= i18n('Upload');?>" />
    <input type="hidden" name="token" value="<?= token();?>" />
</form>
