<?php
namespace app;
use attr;
use layout;
/** @var callable $§ */
?>
<section id="<?=$§('id');?>">
    <h1><?=$§('title');?></h1>
<?php if ($§('data')):?>
    <?php foreach ($§('data') as $data):?>
    <article>
        <?php foreach ($§('attr') as $attr):?>
            <?php if (!$html = attr\viewer($attr, $data)) continue;?>
            <?php if ($attr['id'] === 'name'):?>
                <?php if (allowed($data['_ent']['id'] . '/view')):?>
        <h1><a href="<?= $data['url'] ?? url($data['_ent']['id'] . '/view/' . $data['id']);?>"><?=$html;?></a></h1>
                <?php else:?>
        <h1><?=$html;?></h1>
                <?php endif;?>
            <?php else:?>
        <div data-attr="<?=$attr['id'];?>">
            <?=$html;?>
        </div>
            <?php endif;?>
        <?php endforeach;?>
    </article>
        <?php endforeach;?>
    <?= layout\§('pager');?>
<?php else:;?>
    <p><?= i18n('No entries found');?></p>
<?php endif;?>
</section>
