<?php
namespace app;
/** @var callable $§ */
?>
<nav id="<?=$§('id');?>">
    <div class="info">
        <?= i18n('%s to %s of %s', $§('offset') + 1, min($§('offset') + $§('limit'), $§('size')), $§('size'));?>
    </div>
    <div class="links">
        <?php foreach ($§('links') as $link):?>
            <?php if (!empty($link['active'])):?>
        <span><?=$link['name'];?></span>
            <?php else:?>
        <a href="<?= url('*/*', $link['params']);?>"><?=$link['name'];?></a>
            <?php endif;?>
        <?php endforeach;?>
    </div>
</nav>
