<?php
namespace app;
use session;
/** @var callable $§ */
?>
<form id="<?=$§('id');?>" method="post">
    <h1><?= i18n('Search');?></h1>
    <input type="search" name="param[q]" value="<?=$§('q');?>" placeholder="<?= i18n('Search Term');?>" />
    <input type="submit" value="search" title="<?= i18n('Search');?>" class="icon" />
    <input type="hidden" name="token" value="<?= session\token();?>" />
</form>
