<?php
namespace app;
use attr;
/** @var callable $§ */
?>
<?php if ($data = $§('data')):?>
<article id="<?=$§('id');?>">
    <?php foreach ($§('attr') as $attr):?>
        <?php if (!$html = attr\viewer($attr, $data)) continue;?>
        <?php if ($attr['id'] === 'name'):?>
    <h1 data-attr="<?=$attr['id'];?>" data-type="<?=$attr['type'];?>"><?=$html;?></h1>
        <?php elseif ($attr['id'] === 'aside'):?>
    <aside data-attr="<?=$attr['id'];?>" data-type="<?=$attr['type'];?>">
        <?=$html;?>
    </aside>
        <?php else:?>
    <div data-attr="<?=$attr['id'];?>" data-type="<?=$attr['type'];?>">
        <?=$html;?>
    </div>
        <?php endif;?>
    <?php endforeach;?>
</article>
<?php endif;?>
