<?php
namespace app;
use attr;
/** @var callable $§ */
?>
<?php if ($data = $§('data')):?>
<article id="<?=$§('id');?>">
    <?php foreach ($§('attr') as $attr):?>
        <?php if (!$html = attr\viewer($data, $attr)) continue;?>
        <?php if ($attr['id'] === 'name'):?>
    <h1 data-attr="<?=$attr['id'];?>"><?=$html;?></h1>
        <?php else:?>
    <div data-attr="<?=$attr['id'];?>">
        <?=$html;?>
    </div>
        <?php endif;?>
    <?php endforeach;?>
</article>
<?php endif;?>
