<?php
namespace app;
use attr;
use request;
/** @var callable $var */
?>
<form class="filter">
    <fieldset>
        <?php foreach ($var('attr') as $attr):?>
        <div data-attr="<?=$attr['id'];?>" data-type="<?=$attr['type'];?>">
            <?=attr\filter($var('data'), $attr);?>
        </div>
        <?php endforeach;?>
        <?php if ($var('search')):?>
        <div data-attr="q" data-type="search">
            <label for="q"><?=i18n('Search');?></label>
            <input id="q" type="search" name="q" value="<?=$var('q');?>" placeholder="<?=i18n('Search Term');?>" />
        </div>
        <?php endif;?>
    </fieldset>
    <div class="action">
        <a href="<?=request\data('url');?>" role="button"><?=i18n('Reset');?></a>
        <input type="submit" value="<?=i18n('Submit');?>" />
    </div>
</form>
