<?php
namespace app;
use attr;
use session;
/** @var callable $var */
?>
<form method="post"<?php if ($var('multipart')):?> enctype="multipart/form-data"<?php endif;?> class="block-form">
    <fieldset>
        <?php foreach ($var('attr') as $attr):?>
        <div data-attr="<?=$attr['id'];?>" data-type="<?=$attr['type'];?>">
            <?=attr\frontend($var('data'), $attr);?>
        </div>
        <?php endforeach;?>
    </fieldset>
    <div class="action">
        <?php if (data('action') === 'edit'):?>
        <a href="<?=url(data('entity_id') . '/admin');?>" role="button"><?=i18n('Back');?></a>
        <?php endif;?>
        <input type="submit" value="<?=i18n('Submit');?>" />
        <input type="hidden" name="token" value="<?=session\token();?>" />
    </div>
</form>
