<?php
namespace app;
/** @var callable $§ */
?>
<meta charset="utf-8" />
<?php if ($§('desc')):?>
<meta name="description" content="<?=enc($§('desc'));?>" />
<?php endif;?>
<meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=1.0" />
<title><?=enc($§('title') ?: cfg('app', 'name'));?></title>
<link rel="stylesheet" href="<?=gui('base.css');?>" />
<link rel="stylesheet" href="<?=gui('all.css');?>" />
<link rel="stylesheet" href="<?=gui('screen.css');?>" media="screen" />
<link rel="stylesheet" href="<?=gui('print.css');?>" media="print" />
<?php if (file_exists(path('ext.gui', 'ext.all.css'))):?>
<link rel="stylesheet" href="<?=gui('ext.all.css');?>" />
<?php endif;?>
<?php if (file_exists(path('ext.gui', 'ext.screen.css'))):?>
<link rel="stylesheet" href="<?=gui('ext.screen.css');?>" media="screen" />
<?php endif;?>
<?php if (file_exists(path('ext.gui', 'ext.print.css'))):?>
<link rel="stylesheet" href="<?=gui('ext.print.css');?>" media="print" />
<?php endif;?>
<script src="<?=gui('html2pdf.js');?>"></script>
<?php if (allowed('account-user')):?>
<script src="<?=gui('ckeditor/ckeditor.js');?>"></script>
<script src="<?=url('app/js');?>"></script>
<script src="<?=gui('admin.js');?>"></script>
<?php endif;?>
<script src="<?=gui('all.js');?>"></script>
<?php if (file_exists(path('ext.gui', 'ext.js'))):?>
<script src="<?=gui('ext.js');?>"></script>
<?php endif;?>
