<?php
namespace app;
use attr;
/** @var callable $var */
$admin = get('action') === 'admin';
$browser = !$admin && get('action') === 'browser';
$entityId = $var('entity_id');
?>
<section class="block block-index">
    <?php if ($var('title')):?>
    <h2><?=$var('title');?></h2>
    <?php endif;?>
    <?php if ($admin && allowed($entityId . '/edit')):?>
    <p><a href="<?=url($entityId . '/edit');?>"><?=i18n('New Entry');?></a></p>
    <?php endif;?>
    <?=$var('search');?>
    <?php if (!$var('data')):?>
    <p><?=i18n('No entries found');?></p>
    <?php elseif ($admin):?>
    <div class="thead">
        <?php foreach ($var('attr') as $attr):?>
        <a href="<?=url($var('url'), ['sort' => $attr['id'], 'dir' => $var('sort') === $attr['id'] && $var('dir') === 'asc' ? 'desc' : 'asc'], true);?>"<?php if ($var('sort') === $attr['id']):?> data-sort="<?=$var('dir');?>"<?php endif;?>><?=$attr['name'];?></a>
        <?php endforeach;?>
        <?php if ($admin || $browser):?>
        <span><?=i18n('Actions');?></span>
        <?php endif;?>
    </div>
    <?php endif;?>
    <?php foreach ($var('data') as $data):?>
    <article>
        <?php foreach ($var('attr') as $attr):?>
            <?php
            $val = $data[$attr['id']] ?? null;
            $html = attr\viewer($data, $attr);
            ?>
            <?php if (!$admin && ($val === null || $val === '' || !$html)) continue;?>
            <?php if ($attr['id'] === 'name'):?>
        <h3 data-attr="<?=$attr['id'];?>" data-type="<?=$attr['type'];?>">
                <?php if (get('public') && allowed($entityId . '/view')):?>
            <a href="<?=$data['url'] ?? url($entityId . '/view/' . $data['id']);?>"><?=$html;?></a>
                <?php else:?>
            <?=$html;?>
                <?php endif;?>
        </h3>
            <?php elseif (in_array($attr['type'], ['audio', 'image', 'video'])):?>
        <figure data-attr="<?=$attr['id'];?>" data-type="<?=$attr['type'];?>"><?=$html;?></figure>
            <?php elseif (in_array($attr['type'], ['date', 'datetime', 'time'])):?>
        <time data-attr="<?=$attr['id'];?>" data-type="<?=$attr['type'];?>"<?php if ($val !== $html):?> datetime="<?=$val;?>"<?php endif;?>><?=$html;?></time>
            <?php elseif ($attr['id'] === 'aside'):?>
        <aside data-attr="<?=$attr['id'];?>" data-type="<?=$attr['type'];?>"><?=$html;?></aside>
            <?php else:?>
        <div data-attr="<?=$attr['id'];?>" data-type="<?=$attr['type'];?>"><?=$html;?></div>
            <?php endif;?>
        <?php endforeach;?>
        <?php if ($admin || $browser):?>
        <footer>
            <?php if ($admin && allowed($entityId . '/view')):?>
            <a href="<?=$data['url'] ?? url($entityId . '/view/' . $data['id']);?>" data-action="view"><?=i18n('View');?></a>
            <?php endif;?>
            <?php if ($admin && allowed($entityId . '/edit')):?>
            <a href="<?=url($entityId . '/edit/' . $data['id']);?>" data-action="edit"><?=i18n('Edit');?></a>
            <?php endif;?>
            <?php if ($admin && allowed($entityId . '/delete')):?>
            <a href="<?=url($entityId . '/delete/' . $data['id']);?>" data-action="delete"><?=i18n('Delete');?></a>
            <?php endif;?>
            <?php if ($browser):?>
            <span data-id="<?=$data['id'];?>" data-url="<?=$data['url'];?>" data-action="select"><?=i18n('Select item');?></span>
            <?php endif;?>
        </footer>
        <?php endif;?>
    </article>
    <?php endforeach;?>
    <?=$var('pager');?>
</section>
