<?php
namespace app;
use attr;
/** @var callable $var */
$admin = get('action') === 'admin';
$browser = !$admin && get('action') === 'browser';
$title = $admin || $browser ? get('entity')['name'] : $var('title');
$h1 = $admin || $browser ? 'h1' : 'h2';
$h2 = $admin || $browser ? 'h2' : 'h3';
$entityId = $var('entity_id');
?>
<section class="block-index">
    <?php if ($title):?>
    <<?=$h1;?>><?=$title;?></<?=$h1;?>>
    <?php endif;?>
    <?php if ($admin && allowed($entityId . '/edit')):?>
    <p class="create"><a href="<?=url($entityId . '/edit');?>" data-action="create"><?=i18n('New Entry');?></a></p>
    <?php endif;?>
    <?php if ($var('filter') || $var('search')):?>
    <form method="get" class="filter">
        <fieldset>
            <?php foreach ($var('filter') as $attr):?>
            <div data-attr="<?=$attr['id'];?>" data-type="<?=$attr['type'];?>">
                <?=attr\filter($var('filter-data'), $attr);?>
            </div>
            <?php endforeach;?>
            <?php if ($var('search')):?>
            <div data-attr="q" data-type="search">
                <label for="q"><?=i18n('Search');?></label>
                <input id="q" type="search" name="q" value="<?=$var('q');?>" placeholder="<?=i18n('Search Term');?>" />
            </div>
            <?php endif;?>
        </fieldset>
        <input type="submit" value="<?=i18n('Submit');?>" />
    </form>
    <?php endif;?>
    <?=$var('pager-top');?>
    <?php if (!$var('data')):?>
    <p><?=i18n('No entries found');?></p>
    <?php elseif ($admin):?>
    <div class="thead">
        <?php foreach ($var('attr') as $attr):?>
        <a href="<?=url($var('url'), ['sort' => $attr['id'], 'dir' => $var('sort') === $attr['id'] && $var('dir') === 'asc' ? 'desc' : 'asc'], true);?>"<?php if ($var('sort') === $attr['id']):?> data-sort="<?=$var('dir');?>"<?php endif;?>><?=$attr['name'];?></a>
        <?php endforeach;?>
        <?php if ($admin):?>
        <span><?=i18n('Actions');?></span>
        <?php endif;?>
    </div>
    <?php endif;?>
    <?php foreach ($var('data') as $data):?>
    <article<?php if ($browser):?> data-id="<?=$data['id'];?>" data-url="<?=$data['url'];?>" title="<?=i18n('Select item');?>"<?php endif;?>>
        <?php foreach ($var('attr') as $attr):?>
            <?php
            $val = $data[$attr['id']] ?? null;
            $html = attr\viewer($data, $attr);
            ?>
            <?php if (!$admin && !$html) continue;?>
            <?php if ($attr['id'] === 'name'):?>
        <<?=$h2;?> data-attr="<?=$attr['id'];?>" data-type="<?=$attr['type'];?>">
                <?php if (get('public') && allowed($entityId . '/view')):?>
            <a href="<?=$data['url'] ?? url($entityId . '/view/' . $data['id']);?>"><?=$html;?></a>
                <?php else:?>
            <?=$html;?>
                <?php endif;?>
        </<?=$h2;?>>
            <?php elseif (in_array($attr['type'], ['audio', 'image', 'video'])):?>
        <figure data-attr="<?=$attr['id'];?>" data-type="<?=$attr['type'];?>"><?=$html;?></figure>
            <?php elseif (in_array($attr['type'], ['date', 'datetime', 'time'])):?>
        <time data-attr="<?=$attr['id'];?>" data-type="<?=$attr['type'];?>"<?php if ($val !== $html):?> datetime="<?=$val;?>"<?php endif;?>><?=$html;?></time>
            <?php elseif ($attr['id'] === 'aside'):?>
        <aside data-attr="<?=$attr['id'];?>" data-type="<?=$attr['type'];?>"><?=$html;?></aside>
            <?php else:?>
        <div data-attr="<?=$attr['id'];?>" data-type="<?=$attr['type'];?>"><?=$html;?></div>
            <?php endif;?>
        <?php endforeach;?>
        <?php if ($admin):?>
        <footer>
            <?php if (allowed($entityId . '/view')):?>
            <a href="<?=$data['url'] ?? url($entityId . '/view/' . $data['id']);?>" data-action="view" title="<?=i18n('View');?>"><?=i18n('View');?></a>
            <?php endif;?>
            <?php if (allowed($entityId . '/edit')):?>
            <a href="<?=url($entityId . '/edit/' . $data['id']);?>" data-action="edit" title="<?=i18n('Edit');?>"><?=i18n('Edit');?></a>
            <?php endif;?>
            <?php if (allowed($entityId . '/delete')):?>
            <a href="<?=url($entityId . '/delete/' . $data['id']);?>" data-action="delete" title="<?=i18n('Delete');?>"><?=i18n('Delete');?></a>
            <?php endif;?>
        </footer>
        <?php endif;?>
    </article>
    <?php endforeach;?>
    <?=$var('pager-bottom');?>
</section>
