<?php
namespace app;
/** @var callable $block */
?>
<nav class="pager">
    <div class="info">
        <?=i18n('%s to %s of %s', $block('min'), $block('max'), $block('size'));?>
    </div>
    <div class="links">
        <?php foreach ($block('links') as $link):?>
            <?php if (!empty($link['active'])):?>
        <span><?=$link['name'];?></span>
            <?php else:?>
        <a href="<?=$link['url'];?>"><?=$link['name'];?></a>
            <?php endif;?>
        <?php endforeach;?>
    </div>
</nav>
