<?php
namespace app;
/** @var callable $var */
?>
<nav class="pager">
    <div class="info">
        <?=$var('info');?>
    </div>
    <div class="links">
        <?php foreach ($var('links') as $link):?>
            <?php if (!empty($link['active'])):?>
        <span><?=$link['name'];?></span>
            <?php else:?>
        <a href="<?=$link['url'];?>"<?php if ($link['action']):?> data-action="<?=$link['action'];?>"<?php endif;?>><?=$link['name'];?></a>
            <?php endif;?>
        <?php endforeach;?>
    </div>
</nav>
