<?php
namespace app;
use attr;
/** @var callable $var */
?>
<?php foreach ($var('attr') as $attr):?>
    <?php $val = $var('data')[$attr['id']] ?? null;?>
    <?php if (!$html = attr\viewer($var('data'), $attr)) continue;?>
    <?php if ($attr['id'] === 'name'):?>
<h2 data-attr="<?=$attr['id'];?>" data-type="<?=$attr['type'];?>"><?=$html;?></h2>
    <?php elseif (preg_match('#^<(audio|img|video)#', $html)):?>
<figure data-attr="<?=$attr['id'];?>" data-type="<?=$attr['type'];?>"><?=$html;?></figure>
    <?php elseif (in_array($attr['type'], ['date', 'datetime', 'time'])):?>
<time data-attr="<?=$attr['id'];?>" data-type="<?=$attr['type'];?>"<?php if ($val !== $html):?> datetime="<?=$val;?>"<?php endif;?>><?=$html;?></time>
    <?php elseif ($attr['id'] === 'aside'):?>
<aside data-attr="<?=$attr['id'];?>" data-type="<?=$attr['type'];?>"><?=$html;?></aside>
    <?php else:?>
<div data-attr="<?=$attr['id'];?>" data-type="<?=$attr['type'];?>"><?=$html;?></div>
    <?php endif;?>
<?php endforeach;?>
