<?php namespace akilli; /** @var callable $§ */?>
<section class="section section-login">
    <header>
        <h1><?= _('Login');?></h1>
    </header>
    <form action="<?= url('*/*');?>" method="post" class="login">
        <fieldset class="data">
            <legend><?= _('Credentials');?></legend>
            <div class="element attribute-name">
                <label for="data-name"><?= _('Name');?> <em class="required"><?= _('Required');?></em></label>
                <input id="data-name" type="text" name="data[name]" required="required" title="<?= _('Please enter your name');?>" />
                <p class="message"><?= _('Please enter your name');?></p>
            </div>
            <div class="element attribute-password">
                <label for="data-password"><?= _('Password');?> <em class="required"><?= _('Required');?></em></label>
                <input id="data-password" type="password" name="data[password]" required="required" title="<?= _('Please enter your password');?>" />
                <p class="message"><?= _('Please enter your password');?></p>
            </div>
        </fieldset>
        <fieldset class="action">
            <input type="submit" value="<?= _('Login');?>" />
            <input type="hidden" name="token" value="<?= token();?>" />
        </fieldset>
    </form>
</section>
