<section class="block block-profile">
    <header>
        <h1><?= akilli\_('Profile');?></h1>
    </header>
    <form action="<?=url\path('*/*');?>" method="post" enctype="multipart/form-data" class="edit">
        <fieldset class="data">
            <legend><?= akilli\_('Credentials');?></legend>
            <div class="element attribute-name">
                <label for="data-name"><?= akilli\_('Name');?> <em class="required"><?= akilli\_('Required');?></em> <em class="unique"><?= akilli\_('Unique');?></em></label>
                <input id="data-name" type="text" name="data[name]" value="<?=$block['data']('item')['name'];?>" required="required" title="<?= akilli\_('Your name');?>" />
                <p class="message"><?= akilli\_('Your name');?></p>
            </div>
            <div class="element attribute-password">
                <label for="data-password"><?= akilli\_('Password');?></label>
                <input id="data-password" type="password" name="data[password]" title="<?= akilli\_('Your password');?>" autocomplete="off" />
                <p class="message"><?= akilli\_('Your password');?></p>
            </div>
        </fieldset>
        <fieldset class="action">
            <input type="submit" name="action[save]" title="<?= akilli\_('Save');?>" value="<?= akilli\_('Save');?>" />
            <input type="hidden" name="token" value="<?= akilli\token();?>" />
        </fieldset>
    </form>
</section>
