<?php namespace akilli; /** @var callable $§ */?>
<form action="<?= url('*/create');?>" method="post">
    <label for="create"><?= _('Number');?></label>
    <input id="create" type="number" name="create" value="1" title="<?= _('Please enter the number of items you want to create');?>" />
    <input type="submit" value="<?= _('Create');?>" />
    <input type="hidden" name="token" value="<?= token();?>" />
    <p class="message"><?= _('Please enter the number of items you want to create');?></p>
</form>
