<?php namespace akilli; /** @var callable $§ */?>
<?php if ($§('data')):?>
<section class="section section-entity">
    <?php if ($§('header')):?>
    <header>
        <h1><?=$§('header');?></h1>
    </header>
    <?php endif;?>
    <?php foreach ($§('data') as $id => $item):?>
    <article>
        <?php foreach ($item['_meta']['attributes'] as $code => $attr):?>
            <?php $attr['action'] = 'section';?>
            <?php if (!$html = $attr['view']($attr, $item)) continue;?>
            <?php if ($code === 'name'):?>
        <header>
            <h2><a href="<?= url($item['_meta']['id'] . '/view', ['id' => $id]);?>" title="<?= _('View this item');?>"><?=$html;?></a></h2>
        </header>
            <?php else:?>
        <div class="attribute-<?=$attr['id'];?>">
            <?=$html;?>
        </div>
            <?php endif;?>
        <?php endforeach;?>
    </article>
    <?php endforeach;?>
</section>
<?php endif;?>
