<?php namespace akilli; /** @var callable $§ */?>
<?php if ($item = $§('item')):?>
<article class="block block-view">
    <?php foreach ($item['_meta']['attributes'] as $code => $attr):?>
        <?php $attr['action'] = 'view';?>
        <?php if (!$html = $attr['view']($attr, $item)) continue;?>
        <?php if ($code === 'name'):?>
    <header>
        <h1><?=$html;?></h1>
    </header>
        <?php else:?>
    <div class="attribute-<?=$attr['id'];?>">
        <?=$html;?>
    </div>
        <?php endif;?>
    <?php endforeach;?>
</article>
<?php endif;?>
