<?php namespace akilli; /** @var array $block */?>
<?php if ($block['data']('data')):?>
<section class="block block-entity">
    <?php if ($block['data']('header')):?>
    <header>
        <h1><?=$block['data']('header');?></h1>
    </header>
    <?php endif;?>
    <?php foreach ($block['data']('data') as $id => $item):?>
    <article>
        <?php foreach ($item['_metadata']['attributes'] as $code => $attribute):?>
            <?php $attribute['action'] = 'block';?>
            <?php if (!$html = $attribute['view']($attribute, $item)) continue;?>
            <?php if ($code === 'name'):?>
        <header>
            <h2><a href="<?= url($item['_metadata']['id'] . '/view', ['id' => $id]);?>" title="<?= _('View this item');?>"><?=$html;?></a></h2>
        </header>
            <?php else:?>
        <div class="attribute-<?=$attribute['id'];?>">
            <?=$html;?>
        </div>
            <?php endif;?>
        <?php endforeach;?>
    </article>
    <?php endforeach;?>
</section>
<?php endif;?>
