<?php namespace qnd; /** @var callable $§ */?>
<?php if ($item = $§('item')):?>
<article class="section section-view">
    <?php foreach ($item['_entity']['attr'] as $code => $attr):?>
        <?php if (!$html = viewer($attr, $item)) continue;?>
        <?php if ($code === 'name'):?>
    <header>
        <h1><?=$html;?></h1>
    </header>
        <?php else:?>
    <div class="attribute-<?=$attr['id'];?>">
        <?=$html;?>
    </div>
        <?php endif;?>
    <?php endforeach;?>
</article>
<?php endif;?>
