<?php namespace akilli; /** @var callable $§ */?>
<section class="section section-list">
    <header>
        <h1><?=$§('header');?></h1>
        <?= §('entity.list.search');?>
    </header>
<?php if ($§('data')):?>
    <?php foreach ($§('data') as $id => $item):?>
    <article>
        <?php foreach ($§('attributes') as $code => $attr):?>
            <?php $attr['action'] = 'list';?>
            <?php if (!$html = viewer($attr, $item)) continue;?>
            <?php if ($code === 'name'):?>
        <header>
                <?php if (allowed('view')):?>
            <h2><a href="<?= url('*/view', ['id' => $id]);?>" title="<?= _('View this item');?>"><?=$html;?></a></h2>
                <?php else:?>
            <h2><?=$html;?></h2>
                <?php endif;?>
        </header>
            <?php else:?>
        <div class="attribute-<?=$attr['id'];?>">
            <?=$html;?>
        </div>
            <?php endif;?>
        <?php endforeach;?>
    </article>
        <?php endforeach;?>
    <?= §('entity.list.pager');?>
<?php else:;?>
    <p><?= _('Nothing created yet');?></p>
<?php endif;?>
</section>
