<?php namespace akilli; /** @var callable $ƒ */?>
<section class="block block-edit">
    <header>
        <h1><?=$ƒ('header');?></h1>
    </header>
    <form action="<?= url('*/*');?>" method="post" enctype="multipart/form-data" class="edit">
        <?php foreach ($ƒ('data') as $id => $item):?>
        <fieldset class="data">
            <legend><?=$item['name'] ? $item['name'] : $ƒ('header');?></legend>
            <?php foreach ($item['_meta']['attributes'] as $code => $attr):?>
                <?php if (!$html = $attr['edit']($attr, $item)) continue;?>
            <div class="element attribute-<?=$attr['id'];?>">
                <?=$html;?>
            </div>
            <?php endforeach;?>
        </fieldset>
        <?php endforeach;?>
        <fieldset class="action">
            <?php if (allowed('index')):?>
            <a role="button" href="<?= url('*/index');?>" title="<?= _('Back');?>"><?= _('Back');?></a>
            <?php endif;?>
            <input type="submit" name="action[save]" title="<?= _('Save');?>" value="<?= _('Save');?>" />
            <input type="hidden" name="token" value="<?= token();?>" />
        </fieldset>
    </form>
</section>
