<div class="pager cf">
    <div class="info">
        <?=i18n\translate('Results %d to %d of %d', $block['data']('offset') + 1, min($block['data']('offset') + $block['data']('limit'), $block['data']('size')), $block['data']('size'));?>
    </div>
    <div class="links">
        <a href="<?=$block['data']('first');?>" title="<?=i18n\translate('First Page');?>"><?=i18n\translate('First Page');?></a>
        <a href="<?=$block['data']('previous');?>" title="<?=i18n\translate('Previous Page');?>"><?=i18n\translate('Previous Page');?></a>
        <span><?=i18n\translate('Page %d of %d', $block['data']('page'), $block['data']('pages'));?></span>
        <a href="<?=$block['data']('next');?>" title="<?=i18n\translate('Next Page');?>"><?=i18n\translate('Next Page');?></a>
        <a href="<?=$block['data']('last');?>" title="<?=i18n\translate('Last Page');?>"><?=i18n\translate('Last Page');?></a>
    </div>
</div>
