<?php namespace qnd; /** @var callable $§ */?>
<?php if ($§('data')):?>
<section class="section section-entity">
    <?php if ($§('title')):?>
    <header>
        <h1><?=$§('title');?></h1>
    </header>
    <?php endif;?>
    <?php foreach ($§('data') as $id => $item):?>
    <article>
        <?php foreach ($item['_entity']['attr'] as $code => $attr):?>
            <?php $attr['context'] = 'section';?>
            <?php if (!$html = viewer($attr, $item)) continue;?>
            <?php if ($code === 'name'):?>
        <header>
            <h2><a href="<?= url($item['_entity']['id'] . '/view', ['id' => $id]);?>"><?=$html;?></a></h2>
        </header>
            <?php else:?>
        <div data-attr="<?=$attr['id'];?>">
            <?=$html;?>
        </div>
            <?php endif;?>
        <?php endforeach;?>
    </article>
    <?php endforeach;?>
</section>
<?php endif;?>
