<?php namespace akilli; /** @var array $block */?>
<section class="block block-list">
    <header>
        <h1><?=$block['data']('header');?></h1>
        <?= view('search');?>
    </header>
<?php if ($block['data']('data')):?>
    <?php foreach ($block['data']('data') as $id => $item):?>
    <article>
        <?php foreach ($block['data']('attributes') as $code => $attr):?>
            <?php $attr['action'] = 'list';?>
            <?php if (!$html = $attr['view']($attr, $item)) continue;?>
            <?php if ($code === 'name'):?>
        <header>
                <?php if (allowed('view')):?>
            <h2><a href="<?= url('*/view', ['id' => $id]);?>" title="<?= _('View this item');?>"><?=$html;?></a></h2>
                <?php else:?>
            <h2><?=$html;?></h2>
                <?php endif;?>
        </header>
            <?php else:?>
        <div class="attribute-<?=$attr['id'];?>">
            <?=$html;?>
        </div>
            <?php endif;?>
        <?php endforeach;?>
    </article>
        <?php endforeach;?>
    <?= view('pager');?>
<?php else:;?>
    <p><?= _('Nothing created yet');?></p>
<?php endif;?>
</section>
