<?php namespace qnd; /** @var callable $§ */?>
<section class="section section-index">
    <header>
        <h1><?=$§('header');?></h1>
        <?= §('entity.index.create');?>
        <?= §('entity.index.search');?>
        <?= §('entity.index.pager');?>
    </header>
    <?php if ($§('data')):?>
    <form action="<?= url('*/*');?>" method="post">
        <fieldset>
            <table>
                <thead>
                    <tr>
                        <th>
                            <input type="checkbox" name="checkall" value="1" title="<?= _('Select all');?>" />
                        </th>
                        <?php foreach ($§('attributes') as $code => $attr):?>
                        <th>
                            <a href="<?=$attr['url'];?>"><?= _($attr['name']);?></a>
                        </th>
                        <?php endforeach;?>
                        <?php if (allowed('edit')):?>
                        <th>
                            <?= _('Edit');?>
                        </th>
                        <?php endif;?>
                        <?php if (allowed('view')):?>
                        <th>
                            <?= _('View');?>
                        </th>
                        <?php endif;?>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($§('data') as $id => $item):?>
                    <tr>
                        <td>
                            <input id="edit-<?=$id;?>-name" type="checkbox" name="edit[<?=$id;?>]" value="1" />
                        </td>
                        <?php foreach ($§('attributes') as $code => $attr):?>
                            <?php $attr['action'] = 'index';?>
                        <td>
                            <?=viewer($attr, $item);?>
                        </td>
                        <?php endforeach;?>
                        <?php if (allowed('edit')):?>
                        <td>
                            <a href="<?= url('*/edit', ['id' => $id]);?>" title="<?= _('Edit this item');?>"><?= _('Edit');?></a>
                        </td>
                        <?php endif;?>
                        <?php if (allowed('view')):?>
                        <td>
                            <a href="<?= url('*/view', ['id' => $id]);?>" title="<?= _('View this item');?>"><?= _('View');?></a>
                        </td>
                        <?php endif;?>
                    </tr>
                    <?php endforeach;?>
                </tbody>
            </table>
        </fieldset>
        <?php if (allowed('delete') || allowed('edit')):?>
        <fieldset class="action">
            <?php if (allowed('delete')):?>
            <input type="submit" value="<?= _('Delete');?>" formaction="<?= url('*/delete');?>" />
            <?php endif;?>
            <?php if (allowed('edit')):?>
            <input type="submit" value="<?= _('Edit');?>" formaction="<?= url('*/edit');?>" />
            <?php endif;?>
            <input type="hidden" name="token" value="<?= token();?>" />
        </fieldset>
        <?php endif;?>
    </form>
    <?php else:;?>
    <p><?= _('Nothing created yet');?></p>
    <?php endif;?>
</section>
