<section class="block block-index">
    <header>
        <h1><?=$block['data']('header');?></h1>
        <div class="tools cf">
            <?=view\render('entity.index.create');?>
            <?=view\render('entity.index.search');?>
        </div>
        <?=view\render('pager');?>
    </header>
    <?php if ($block['data']('data')):?>
    <form action="<?=url\path('*/*');?>" method="post" class="index">
        <fieldset class="data">
            <table>
                <thead>
                    <tr>
                        <th data-type="bool.checkbox">
                            <input type="checkbox" name="gui[checkall]" value="1" title="<?=i18n\translate('Select all');?>" />
                        </th>
                        <?php foreach ($block['data']('attributes') as $code => $attribute):?>
                        <th data-type="<?=$attribute['backend'];?>.<?=$attribute['frontend'];?>">
                            <a href="<?=$attribute['url'];?>"><?=i18n\translate($attribute['name']);?></a>
                        </th>
                        <?php endforeach;?>
                        <?php if (role\allowed('edit')):?>
                        <th data-type="bool.checkbox">
                            <?=i18n\translate('Edit');?>
                        </th>
                        <?php endif;?>
                        <?php if (role\allowed('view')):?>
                        <th data-type="bool.checkbox">
                            <?=i18n\translate('View');?>
                        </th>
                        <?php endif;?>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($block['data']('data') as $id => $item):?>
                    <tr>
                        <td>
                            <input id="data-<?=$id;?>-name" type="checkbox" name="data[<?=$id;?>]" value="1" />
                        </td>
                        <?php foreach ($block['data']('attributes') as $code => $attribute):?>
                            <?php $attribute['action'] = 'index';?>
                        <td>
                            <?=$attribute['view']($attribute, $item);?>
                        </td>
                        <?php endforeach;?>
                        <?php if (role\allowed('edit')):?>
                        <td>
                            <a href="<?=url\path('*/edit', ['id' => $id]);?>" title="<?=i18n\translate('Edit this item');?>"><?=i18n\translate('Edit');?></a>
                        </td>
                        <?php endif;?>
                        <?php if (role\allowed('view')):?>
                        <td>
                            <a href="<?=url\path('*/view', ['id' => $id]);?>" title="<?=i18n\translate('View this item');?>"><?=i18n\translate('View');?></a>
                        </td>
                        <?php endif;?>
                    </tr>
                    <?php endforeach;?>
                </tbody>
            </table>
        </fieldset>
        <?php if (role\allowed('delete') || role\allowed('edit')):?>
        <fieldset class="action">
            <?php if (role\allowed('delete')):?>
            <input type="submit" name="action[delete]" title="<?=i18n\translate('Delete');?>" value="<?=i18n\translate('Delete');?>" formaction="<?=url\path('*/delete');?>" />
            <?php endif;?>
            <?php if (role\allowed('edit')):?>
            <input type="submit" name="action[edit]" title="<?=i18n\translate('Edit');?>" value="<?=i18n\translate('Edit');?>" formaction="<?=url\path('*/edit');?>" />
            <?php endif;?>
            <input type="hidden" name="token" value="<?=session\token();?>" />
        </fieldset>
        <?php endif;?>
    </form>
    <?php else:;?>
    <p><?=i18n\translate('Nothing created yet');?></p>
    <?php endif;?>
</section>
