<?php namespace qnd; /** @var callable $§ */?>
<meta charset="<?= config('i18n.charset');?>" />
<?php foreach (array_replace(config('meta'), (array) $§('meta')) as $name => $content):?>
<meta name="<?=$name;?>" content="<?=$content;?>" />
<?php endforeach;?>
<title><?=$§('title');?> <?=config('meta.separator');?> <?=config('meta.title');?></title>
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Ubuntu:300,400" />
<link rel="stylesheet" href="<?=url_css('base.css');?>" />
<link rel="stylesheet" href="<?=url_css('theme.css');?>" />
<link rel="shortcut icon" href="<?= url_media('favicon.png');?>" />
