<?php namespace qnd; /** @var callable $§ */?>
<meta charset="<?= config('i18n.charset');?>" />
<?php foreach (array_replace(config('meta'), (array) $§('meta')) as $name => $content):?>
<meta name="<?=$name;?>" content="<?=$content;?>" />
<?php endforeach;?>
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
<title><?=$§('title');?></title>
<link rel="stylesheet" href="<?=url_css('base.css');?>" />
<link rel="stylesheet" href="<?=url_css('theme.css');?>" />
<link rel="stylesheet" href="<?=url_css('toolbar.css');?>" />
