<?php namespace qnd; /** @var callable $§ */?>
<meta charset="<?= config('i18n.charset');?>" />
<?php foreach ($§('meta') as $name => $content):?>
<meta name="<?=$name;?>" content="<?=$content;?>" />
<?php endforeach;?>
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
<title><?=$§('title');?></title>
<link rel="stylesheet" href="<?=url_theme('css/base.css');?>" />
<link rel="stylesheet" href="<?=url_theme('css/theme.css');?>" />
<link rel="stylesheet" href="<?=url_theme('css/toolbar.css');?>" />
