<?php namespace akilli; /** @var array $block */?>
<!DOCTYPE html>
<html lang="<?= config('i18n.language');?>">
    <head>
        <?= view('head');?>
    </head>
    <body class="<?=$block['data']('class');?>">
        <?= view('top');?>
        <?= view('message');?>
        <div id="content" class="cf">
            <aside id="left">
                <?= view('left');?>
            </aside>
            <main>
                <?= view('content');?>
            </main>
            <aside id="right">
                <?= view('right');?>
            </aside>
        </div>
        <?= view('bottom');?>
    </body>
</html>
