<!DOCTYPE html>
<html lang="<?= akilli\config('i18n.language');?>">
    <head>
        <?= akilli\view_render('head');?>
    </head>
    <body class="<?=$block['data']('class');?>">
        <?= akilli\view_render('top');?>
        <?= akilli\view_render('message');?>
        <div id="content" class="cf">
            <aside id="left">
                <?= akilli\view_render('left');?>
            </aside>
            <main>
                <?= akilli\view_render('content');?>
            </main>
            <aside id="right">
                <?= akilli\view_render('right');?>
            </aside>
        </div>
        <?= akilli\view_render('bottom');?>
    </body>
</html>
