<?php namespace akilli; /** @var callable $§ */?>
<!DOCTYPE html>
<html lang="<?= config('i18n.language');?>">
    <head>
        <?= §('head');?>
    </head>
    <body class="<?=$§('class');?>">
        <?= §('top');?>
        <?= §('message');?>
        <div id="content" class="cf">
            <aside id="left">
                <?= §('left');?>
            </aside>
            <main>
                <?= §('content');?>
            </main>
            <aside id="right">
                <?= §('right');?>
            </aside>
        </div>
        <?= §('bottom');?>
    </body>
</html>
