<?php namespace qnd; /** @var callable $§ */?>
<section id="<?=$§('§')['as'];?>" class="index">
    <h1><?=$§('title');?></h1>
    <div class="tool">
        <form action="<?= url('*/create');?>" method="post">
            <label for="create"><?= _('New Entry');?></label>
            <input id="create" type="number" name="create" value="1" />
            <input type="submit" value="<?= _('Create');?>" />
            <input type="hidden" name="token" value="<?= token();?>" />
        </form>
        <?= §('search');?>
    </div>
    <?= §('pager');?>
    <?php if ($§('data')):?>
        <?php
        $params = array_replace(['sort' => null, 'dir' => null], $§('params'));
        if (array_key_exists('page', $params) && $params['page'] <= 1) unset($params['page']);
        ?>
    <form action="<?= url('*/*');?>" method="post">
        <fieldset>
            <table>
                <thead>
                    <tr>
                        <th>
                            <input type="checkbox" name="checkall" value="1" title="<?= _('Select all');?>" />
                        </th>
                        <?php foreach ($§('attr') as $code => $attr):?>
                            <?php $dir = $params['sort'] === $code && $params['dir'] === 'asc' ? 'desc' : 'asc'; ?>
                        <th>
                            <a href="<?= url('*/*', array_replace($params, ['sort' => $code, 'dir' => $dir]));?>"><?= _($attr['name']);?></a>
                        </th>
                        <?php endforeach;?>
                        <?php if (allowed('edit')):?>
                        <th>
                            <?= _('Edit');?>
                        </th>
                        <?php endif;?>
                        <?php if (allowed('view')):?>
                        <th>
                            <?= _('View');?>
                        </th>
                        <?php endif;?>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($§('data') as $id => $item):?>
                    <tr>
                        <td>
                            <input id="edit-<?=$id;?>-name" type="checkbox" name="edit[<?=$id;?>]" value="1" />
                        </td>
                        <?php foreach ($§('attr') as $code => $attr):?>
                            <?php $attr['context'] = 'index';?>
                        <td>
                            <?=viewer($attr, $item);?>
                        </td>
                        <?php endforeach;?>
                        <?php if (allowed('edit')):?>
                        <td>
                            <a href="<?= url('*/edit', ['id' => $id]);?>"><?= _('Edit');?></a>
                        </td>
                        <?php endif;?>
                        <?php if (allowed('view')):?>
                        <td>
                            <a href="<?= url('*/view', ['id' => $id]);?>"><?= _('View');?></a>
                        </td>
                        <?php endif;?>
                    </tr>
                    <?php endforeach;?>
                </tbody>
            </table>
        </fieldset>
        <?php if (allowed('delete')):?>
        <input type="submit" value="<?= _('Delete');?>" formaction="<?= url('*/delete');?>" />
        <?php endif;?>
        <?php if (allowed('edit')):?>
        <input type="submit" value="<?= _('Edit');?>" formaction="<?= url('*/edit');?>" />
        <?php endif;?>
        <?php if (allowed('delete') || allowed('edit')):?>
        <input type="hidden" name="token" value="<?= token();?>" />
        <?php endif;?>
    </form>
    <?php else:;?>
    <p><?= _('Nothing created yet');?></p>
    <?php endif;?>
</section>
