<?php namespace qnd; /** @var callable $§ */?>
<section id="<?=$§('§')['as'];?>" class="list">
    <h1><?=$§('title');?></h1>
<?php if ($§('data')):?>
    <?= §('search');?>
    <?php foreach ($§('data') as $id => $item):?>
    <article>
        <?php foreach ($§('attr') as $attr):?>
            <?php $attr['context'] = 'list';?>
            <?php if (!$html = viewer($attr, $item)) continue;?>
            <?php if ($attr['id'] === 'name'):?>
                <?php if (allowed('view')):?>
        <h1><a href="<?= url('*/view', ['id' => $id]);?>"><?=$html;?></a></h1>
                <?php else:?>
        <h1><?=$html;?></h1>
                <?php endif;?>
            <?php else:?>
        <div data-attr="<?=$attr['id'];?>">
            <?=$html;?>
        </div>
            <?php endif;?>
        <?php endforeach;?>
    </article>
        <?php endforeach;?>
    <?= §('pager');?>
<?php else:;?>
    <p><?= _('Nothing created yet');?></p>
<?php endif;?>
</section>
