<?php namespace qnd; /** @var callable $§ */?>
<div id="<?=$§('§')['as'];?>">
    <div class="info">
        <?= _('Results %d to %d of %d', $§('offset') + 1, min($§('offset') + $§('limit'), $§('size')), $§('size'));?>
    </div>
    <div class="links">
        <a href="<?=$§('first');?>"><?= _('First Page');?></a>
        <a href="<?=$§('prev');?>" rel="prev"><?= _('Previous Page');?></a>
        <span><?= _('Page %d of %d', $§('page'), $§('pages'));?></span>
        <a href="<?=$§('next');?>" rel="next"><?= _('Next Page');?></a>
        <a href="<?=$§('last');?>"><?= _('Last Page');?></a>
    </div>
</div>
