<?php namespace qnd; /** @var callable $§ */?>
<!DOCTYPE html>
<html>
    <head>
        <?= §('head');?>
    </head>
    <body>
        <?= §('top');?>
        <?= §('message');?>
        <?php if ($html = §('left')):?>
        <aside id="left">
            <?= $html;?>
        </aside>
        <?php endif;?>
        <main>
            <?= §('content');?>
        </main>
        <?php if ($html = §('right')):?>
        <aside id="right">
            <?= $html;?>
        </aside>
        <?php endif;?>
        <?= §('bottom');?>
    </body>
</html>
