<?php namespace qnd; /** @var callable $§ */?>
<!DOCTYPE html>
<html data-id="<?= request('id');?>" data-entity="<?= request('entity');?>" data-action="<?= request('action');?>">
    <head>
        <?= §('head');?>
    </head>
    <body>
        <?= §('top');?>
        <?php if ($html = §('left')):?>
        <aside id="left">
            <?= $html;?>
        </aside>
        <?php endif;?>
        <main>
            <?= §('message');?>
            <?= §('main');?>
        </main>
        <?php if ($html = §('right')):?>
        <aside id="right">
            <?= $html;?>
        </aside>
        <?php endif;?>
        <?= §('bottom');?>
    </body>
</html>
