<?php namespace qnd; /** @var callable $§ */?>
<?php if ($§('data')):?>
<section id="<?=$§('§')['as'];?>" class="section">
    <?php if ($§('title')):?>
    <h1><?=$§('title');?></h1>
    <?php endif;?>
    <?php foreach ($§('data') as $id => $item):?>
    <article>
        <?php foreach ($item['_entity']['attr'] as $attr):?>
            <?php $attr['context'] = 'section';?>
            <?php if (!$html = viewer($attr, $item)) continue;?>
            <?php if ($attr['id'] === 'name'):?>
        <h1><a href="<?= url($item['_entity']['id'] . '/view', ['id' => $id]);?>"><?=$html;?></a></h1>
            <?php else:?>
        <div data-attr="<?=$attr['id'];?>">
            <?=$html;?>
        </div>
            <?php endif;?>
        <?php endforeach;?>
    </article>
    <?php endforeach;?>
</section>
<?php endif;?>
