<ul>
    <?php foreach ((array) $block['data']('data') as $item):?>
    <li>
        <?php if ($item['url']):?>
        <a href="<?=$item['url'];?>" title="<?= akilli\_($item['description']);?>"><?= akilli\_($item['name']);?></a>
        <?php else:?>
        <span title="<?= akilli\_($item['description']);?>"><?= akilli\_($item['name']);?></span>
        <?php endif;?>
        <?=$item['children'];?>
    </li>
    <?php endforeach;?>
</ul>
