<nav id="toolbar" class="cf">
    <ul>
        <li class="toolbar">
            <a href="<?= akilli\url('account/dashboard');?>" title="<?= akilli\_('Dashboard');?>"><?= akilli\_('Dashboard');?></a>
            <?= akilli\view_render('toolbar.menu');?>
        </li>
        <li><a href="<?= akilli\url();?>" title="<?= akilli\_('Homepage');?>"><?= akilli\_('Homepage');?></a></li>
        <li><a href="<?= akilli\url('account/profile');?>" title="<?= akilli\_('Profile');?>"><?= akilli\_('Profile');?></a></li>
        <li><a href="<?= akilli\url('account/logout');?>" title="<?= akilli\_('Logout');?>"><?= akilli\_('Logout');?></a></li>
    </ul>
</nav>
