<nav id="toolbar" class="cf">
    <ul>
        <li class="toolbar">
            <a href="<?=url\path('account/dashboard');?>" title="<?= akilli\_('Dashboard');?>"><?= akilli\_('Dashboard');?></a>
            <?=view\render('toolbar.menu');?>
        </li>
        <li><a href="<?=url\path();?>" title="<?= akilli\_('Homepage');?>"><?= akilli\_('Homepage');?></a></li>
        <li><a href="<?=url\path('account/profile');?>" title="<?= akilli\_('Profile');?>"><?= akilli\_('Profile');?></a></li>
        <li><a href="<?=url\path('account/logout');?>" title="<?= akilli\_('Logout');?>"><?= akilli\_('Logout');?></a></li>
    </ul>
</nav>
