<?php namespace akilli; /** @var array $block */?>
<ul>
    <?php foreach ((array) $block['data']('data') as $item):?>
    <li>
        <?php if ($item['url']):?>
        <a href="<?=$item['url'];?>" title="<?= _($item['description']);?>"><?= _($item['name']);?></a>
        <?php else:?>
        <span title="<?= _($item['description']);?>"><?= _($item['name']);?></span>
        <?php endif;?>
        <?=$item['children'];?>
    </li>
    <?php endforeach;?>
</ul>
