<?php namespace akilli; /** @var callable $ƒ */?>
<ul>
    <?php foreach ((array) $ƒ('data') as $item):?>
    <li>
        <?php if ($item['url']):?>
        <a href="<?=$item['url'];?>" title="<?= _($item['description']);?>"><?= _($item['name']);?></a>
        <?php else:?>
        <span title="<?= _($item['description']);?>"><?= _($item['name']);?></span>
        <?php endif;?>
        <?=$item['children'];?>
    </li>
    <?php endforeach;?>
</ul>
