<?php namespace qnd; /** @var callable $§ */?>
<nav id="toolbar">
    <ul>
        <li class="toolbar">
            <a href="<?= url('user/dashboard');?>"><?= _('Dashboard');?></a>
            <?= §('toolbar.list');?>
        </li>
        <li><a href="<?= url();?>"><?= _('Homepage');?></a></li>
        <li><a href="<?= url('user/profile');?>"><?= _('Profile');?></a></li>
        <li><a href="<?= url('user/logout');?>"><?= _('Logout');?></a></li>
    </ul>
</nav>
