<?php namespace qnd; /** @var callable $§ */?>
<section class="section section-login">
    <header>
        <h1><?= _('Login');?></h1>
    </header>
    <form action="<?= url('*/*');?>" method="post" class="login">
        <fieldset>
            <legend><?= _('Credentials');?></legend>
            <div data-attr="username">
                <label for="data-username"><?= _('Username');?> <em class="required"><?= _('Required');?></em></label>
                <input id="data-username" type="text" name="data[username]" required="required" />
            </div>
            <div data-attr="password">
                <label for="data-password"><?= _('Password');?> <em class="required"><?= _('Required');?></em></label>
                <input id="data-password" type="password" name="data[password]" required="required" />
            </div>
        </fieldset>
        <input type="submit" value="<?= _('Login');?>" />
        <input type="hidden" name="token" value="<?= token();?>" />
    </form>
</section>
