<?php namespace qnd; /** @var callable $§ */?>
<section class="section section-login">
    <header>
        <h1><?= _('Login');?></h1>
    </header>
    <form action="<?= url('*/*');?>" method="post" class="login">
        <fieldset class="data">
            <legend><?= _('Credentials');?></legend>
            <div class="element attr-username">
                <label for="data-username"><?= _('Username');?> <em class="required"><?= _('Required');?></em></label>
                <input id="data-username" type="text" name="data[username]" required="required" />
            </div>
            <div class="element attr-password">
                <label for="data-password"><?= _('Password');?> <em class="required"><?= _('Required');?></em></label>
                <input id="data-password" type="password" name="data[password]" required="required" />
            </div>
        </fieldset>
        <fieldset class="action">
            <input type="submit" value="<?= _('Login');?>" />
            <input type="hidden" name="token" value="<?= token();?>" />
        </fieldset>
    </form>
</section>
