<?php namespace qnd; /** @var callable $§ */?>
<section class="section section-profile">
    <header>
        <h1><?= _('Profile');?></h1>
    </header>
    <form action="<?= url('*/*');?>" method="post" enctype="multipart/form-data" class="edit">
        <fieldset class="data">
            <legend><?= _('Credentials');?></legend>
            <div class="element attribute-name">
                <label for="data-name"><?= _('Name');?> <em class="required"><?= _('Required');?></em></label>
                <input id="data-name" type="text" name="data[name]" value="<?=$§('item')['name'];?>" required="required" />
            </div>
            <div class="element attribute-email">
                <label for="data-email"><?= _('Email');?> <em class="required"><?= _('Required');?></em> <em class="unambiguous"><?= _('Unambiguous');?></em></label>
                <input id="data-email" type="email" name="data[email]" value="<?=$§('item')['email'];?>" required="required" />
            </div>
            <div class="element attribute-password">
                <label for="data-password"><?= _('Password');?></label>
                <input id="data-password" type="password" name="data[password]" autocomplete="off" />
            </div>
        </fieldset>
        <fieldset class="action">
            <input type="submit" value="<?= _('Save');?>" />
            <input type="hidden" name="token" value="<?= token();?>" />
        </fieldset>
    </form>
</section>
