<?php namespace qnd; /** @var callable $§ */?>
<?php if ($item = $§('item')):?>
<article id="<?=$§('§')['as'];?>" class="view">
    <?php foreach ($item['_entity']['attr'] as $attr):?>
        <?php if (!$html = viewer($attr, $item)) continue;?>
        <?php if ($attr['id'] === 'name'):?>
    <h1><?=$html;?></h1>
        <?php else:?>
    <div data-attr="<?=$attr['id'];?>">
        <?=$html;?>
    </div>
        <?php endif;?>
    <?php endforeach;?>
</article>
<?php endif;?>
