<?php
namespace app;
use session;
/** @var callable $§ */
?>
<section id="<?=$§('id');?>">
    <h1><?= i18n('Password');?></h1>
    <form method="post">
        <fieldset>
            <legend><?= i18n('Change password');?></legend>
            <div data-attr="password" data-type="password">
                <label for="data-password"><?= i18n('Password');?></label>
                <input id="data-password" type="password" name="data[password]" required="required" autocomplete="off" />
            </div>
            <div data-attr="confirmation" data-type="password">
                <label for="data-confirmation"><?= i18n('Password Confirmation');?></label>
                <input id="data-confirmation" type="password" name="data[confirmation]" required="required" autocomplete="off" />
            </div>
        </fieldset>
        <input type="submit" value="<?= i18n('Save');?>" />
        <input type="hidden" name="token" value="<?= session\token();?>" />
    </form>
</section>
