<?php
namespace app;
use session;
/** @var callable $§ */
?>
<section id="<?=$§('id');?>">
    <h1><?=i18n('Password');?></h1>
    <form method="post">
        <fieldset>
            <div data-attr="password">
                <label for="data-password"><?=i18n('Password');?></label>
                <input id="data-password" type="password" name="data[password]" required="required" autocomplete="off" data-type="password" />
                <?php if ($§('error')):?>
                <div class="error"><?=$§('error');?></div>
                <?php endif;?>
            </div>
            <div data-attr="confirmation">
                <label for="data-confirmation"><?=i18n('Password Confirmation');?></label>
                <input id="data-confirmation" type="password" name="data[confirmation]" required="required" autocomplete="off" data-type="password" />
            </div>
        </fieldset>
        <input type="submit" value="<?=i18n('Save');?>" />
        <input type="hidden" name="token" value="<?=session\token();?>" />
    </form>
</section>
