<?php namespace qnd; /** @var callable $§ */?>
<section id="<?=$§('§')['as'];?>" class="edit">
    <h1><?=$§('title');?></h1>
    <form method="post" enctype="multipart/form-data">
        <?php foreach ($§('data') as $id => $item):?>
        <fieldset>
            <legend><?=$item['name'] ?? _('New Entry');?></legend>
            <?php foreach ($item['_entity']['attr'] as $attr):?>
                <?php if (!$html = editor($attr, $item)) continue;?>
            <div data-attr="<?=$attr['id'];?>">
                <?=$html;?>
            </div>
            <?php endforeach;?>
        </fieldset>
        <?php endforeach;?>
        <?php if (allowed('index')):?>
        <a role="button" href="<?= url('*/index');?>"><?= _('Back');?></a>
        <?php endif;?>
        <input type="submit" value="<?= _('Save');?>" />
        <input type="hidden" name="token" value="<?= token();?>" />
    </form>
</section>
