<?php
namespace app;
use attr;
/** @var callable $block */
$admin = get('action') === 'admin';
$browser = !$admin && get('action') === 'browser';
?>
<section class="index">
    <?php if ($block('title')):?>
    <h2><?=$block('title');?></h2>
    <?php endif;?>
    <?php if ($admin && allowed($block('entity')['id'] . '/edit')):?>
    <p><a href="<?=url($block('entity')['id'] . '/edit');?>"><?=i18n('New Entry');?></a></p>
    <?php endif;?>
    <?=$block('search');?>
    <?php if (!$block('data')):?>
    <p><?=i18n('No entries found');?></p>
    <?php elseif ($admin):?>
    <div class="thead">
        <?php foreach ($block('attr') as $attrId):?>
            <?php if (!($attr = $block('entity')['attr'][$attrId] ?? null)) continue;?>
        <a href="<?=url($block('url'), ['sort' => $attr['id'], 'dir' => $block('sort') === $attr['id'] && $block('dir') === 'asc' ? 'desc' : 'asc'], true);?>"<?php if ($block('sort') === $attr['id']):?> data-sort="<?=$block('dir');?>"<?php endif;?>><?=$attr['name'];?></a>
        <?php endforeach;?>
        <?php if ($admin || $browser):?>
        <span><?=i18n('Actions');?></span>
        <?php endif;?>
    </div>
    <?php endif;?>
    <?php foreach ($block('data') as $data):?>
    <article>
        <?php foreach ($block('attr') as $attrId):?>
            <?php if (!($attr = $block('entity')['attr'][$attrId] ?? null)) continue;?>
            <?php
            $val = $data[$attr['id']] ?? null;
            $html = attr\viewer($data, $attr);
            ?>
            <?php if (!$admin && ($val === null || $val === '' || !$html)) continue;?>
            <?php if ($attr['id'] === 'name'):?>
        <h3 data-attr="<?=$attr['id'];?>" data-type="<?=$attr['type'];?>">
                <?php if (get('public') && allowed($block('entity')['id'] . '/view')):?>
            <a href="<?=$data['url'] ?? url($block('entity')['id'] . '/view/' . $data['id']);?>"><?=$html;?></a>
                <?php else:?>
            <?=$html;?>
                <?php endif;?>
        </h3>
            <?php elseif (in_array($attr['type'], ['date', 'datetime', 'time'])):?>
        <time data-attr="<?=$attr['id'];?>" data-type="<?=$attr['type'];?>"<?php if ($val !== $html):?> datetime="<?=$val;?>"<?php endif;?>><?=$html;?></time>
            <?php elseif ($attr['id'] === 'aside'):?>
        <aside data-attr="<?=$attr['id'];?>" data-type="<?=$attr['type'];?>">
            <?=$html;?>
        </aside>
            <?php else:?>
        <div data-attr="<?=$attr['id'];?>" data-type="<?=$attr['type'];?>">
            <?=$html;?>
        </div>
            <?php endif;?>
        <?php endforeach;?>
        <?php if ($admin || $browser):?>
        <footer>
            <?php if ($admin && allowed($block('entity')['id'] . '/view')):?>
            <a href="<?=$data['url'] ?? url($block('entity')['id'] . '/view/' . $data['id']);?>" data-action="view"><?=i18n('View');?></a>
            <?php endif;?>
            <?php if ($admin && allowed($block('entity')['id'] . '/edit')):?>
            <a href="<?=url($block('entity')['id'] . '/edit/' . $data['id']);?>" data-action="edit"><?=i18n('Edit');?></a>
            <?php endif;?>
            <?php if ($admin && allowed($block('entity')['id'] . '/delete')):?>
            <a href="<?=url($block('entity')['id'] . '/delete/' . $data['id']);?>" data-action="delete"><?=i18n('Delete');?></a>
            <?php endif;?>
            <?php if ($browser):?>
            <span data-id="<?=$data['id'];?>" data-url="<?=$data['name'];?>" data-action="select"><?=i18n('Select item');?></span>
            <?php endif;?>
        </footer>
        <?php endif;?>
    </article>
    <?php endforeach;?>
    <?=$block('pager');?>
</section>
