<?php
namespace app;
use attr;
/** @var callable $block */
?>
<?php foreach ($block('attr') as $attrId):?>
    <?php
    $attr = $block('entity')['attr'][$attrId] ?? null;
    $val = $block('data')[$attrId] ?? null;
    ?>
    <?php if (!$attr || $val === null || $val === '' || !($html = attr\viewer($block('data'), $attr))) continue;?>
    <?php if ($attr['id'] === 'name'):?>
<h1 data-attr="<?=$attr['id'];?>" data-type="<?=$attr['type'];?>"><?=$html;?></h1>
    <?php elseif (in_array($attr['type'], ['audio', 'image', 'video'])):?>
<figure data-attr="<?=$attr['id'];?>" data-type="<?=$attr['type'];?>"><?=$html;?></figure>
    <?php elseif (in_array($attr['type'], ['date', 'datetime', 'time'])):?>
<time data-attr="<?=$attr['id'];?>" data-type="<?=$attr['type'];?>"<?php if ($val !== $html):?> datetime="<?=$val;?>"<?php endif;?>><?=$html;?></time>
    <?php elseif ($attr['id'] === 'aside'):?>
<aside data-attr="<?=$attr['id'];?>" data-type="<?=$attr['type'];?>"><?=$html;?></aside>
    <?php else:?>
<div data-attr="<?=$attr['id'];?>" data-type="<?=$attr['type'];?>"><?=$html;?></div>
    <?php endif;?>
<?php endforeach;?>
