<?php
return [
    'attr' => [
        'id' => null,
        'name' => null,
        'col' => null,
        'auto' => false,
        'sort' => 0,
        'type' => null,
        'backend' => null,
        'frontend' => null,
        'db_type' => null,
        'pdo' => null,
        'nullable' => false,
        'required' => false,
        'uniq' => false,
        'multiple' => false,
        'searchable' => false,
        'opt' => [],
        'actions' => [],
        'val' => null,
        'minval' => 0,
        'maxval' => 0,
        'entity' => null,
        'context' => null,
        'html' => [],
        'validator' => null,
        'saver' => null,
        'loader' => null,
        'editor' => null,
        'viewer' => null,
    ],
    'entity' => [
        'id' => null,
        'name' => null,
        'tab' => null,
        'model' => 'flat',
        'actions' => [],
        'attr' => [],
    ],
    'entity.opts' => [
        'mode' => 'all',
        'index' => 'id',
        'order' => [],
        'limit' => 0,
        'offset' => 0
    ],
    'section' => [
        'id' => null,
        'type' => null,
        'template' => null,
        'vars' => [],
        'active' => true,
        'privilege' => null,
        'parent' => 'root',
        'sort' => 0,
        'children' => [],
    ],
];
