<?php namespace qnd; /** @var callable $§ */?>
<nav id="<?=$§('§')['as'];?>">
    <?php if (allowed('project.switch')):?>
    <form id="toolbar-project" action="<?= url('project/switch');?>" method="post">
        <label for="toolbar-project-id"><?= _('Project');?></label>
        <select id="toolbar-project-id" name="id">
            <?php foreach (all('project', ['active' => true]) as $project):?>
            <option value="<?= $project['id'];?>" <?php if (project('id') === $project['id']):?> selected="selected"<?php endif;?>><?= $project['name'];?></option>
            <?php endforeach;?>
        </select>
        <input type="submit" value="<?= _('Switch');?>" />
        <input type="hidden" name="token" value="<?= token();?>" />
    </form>
    <?php endif;?>
    <?php if ($data = data('toolbar')):?>
    <ul>
        <?php foreach ($data as $item):?>
        <li>
            <?php if ($item['url']):?>
            <a href="<?=$item['url'];?>"><?=$item['name'];?></a>
            <?php else:?>
            <span><?=$item['name'];?></span>
            <?php endif;?>
            <?php if (!empty($item['children'])):?>
            <ul>
                <?php foreach ($item['children'] as $child):?>
                <li>
                    <a href="<?=$child['url'];?>"><?=$child['name'];?></a>
                </li>
                <?php endforeach;?>
            </ul>
            <?php endif;?>
        </li>
        <?php endforeach;?>
    </ul>
    <?php endif;?>
</nav>
