<?php namespace qnd; /** @var callable $§ */?>
<section id="<?=$§('id');?>">
    <h1><?= _('Login');?></h1>
    <form method="post">
        <fieldset>
            <div data-attr="name">
                <label for="data-name"><?= _('Name');?> <em class="required"><?= _('Required');?></em></label>
                <input id="data-name" type="text" name="data[name]" required="required" />
            </div>
            <div data-attr="password">
                <label for="data-password"><?= _('Password');?> <em class="required"><?= _('Required');?></em></label>
                <input id="data-password" type="password" name="data[password]" required="required" />
            </div>
        </fieldset>
        <input type="submit" value="<?= _('Login');?>" />
        <input type="hidden" name="token" value="<?= token();?>" />
    </form>
</section>
