<?php namespace qnd; /** @var callable $§ */?>
<section id="<?=$§('§')['id'];?>">
    <h1><?= _('Password');?></h1>
    <form method="post">
        <fieldset>
            <legend><?= _('Change password');?></legend>
            <div data-attr="password">
                <label for="data-password"><?= _('Password');?></label>
                <input id="data-password" type="password" name="data[password]" required="required" autocomplete="off" />
            </div>
            <div data-attr="confirmation">
                <label for="data-confirmation"><?= _('Password Confirmation');?></label>
                <input id="data-confirmation" type="password" name="data[confirmation]" required="required" autocomplete="off" />
            </div>
        </fieldset>
        <input type="submit" value="<?= _('Save');?>" />
        <input type="hidden" name="token" value="<?= token();?>" />
    </form>
</section>
