<?php namespace qnd; /** @var callable $§ */?>
<section id="<?=$§('§')['id'];?>">
    <h1><?= _('Profile');?></h1>
    <form method="post" enctype="multipart/form-data">
        <fieldset>
            <legend><?= _('Profile Data');?></legend>
            <div data-attr="password">
                <label for="data-password"><?= _('Password');?></label>
                <input id="data-password" type="password" name="data[password]" autocomplete="off" />
            </div>
        </fieldset>
        <input type="submit" value="<?= _('Save');?>" />
        <input type="hidden" name="token" value="<?= token();?>" />
    </form>
</section>
