#!/bin/bash

_opt=""

if [ "$DOCKER_TAG" == "next" ]; then
    _opt="--build-arg TAG=next"
fi

echo "docker build ${_opt} -f ${DOCKERFILE_PATH} -t ${IMAGE_NAME} ."
docker build ${_opt} -f ${DOCKERFILE_PATH} -t ${IMAGE_NAME} .
