#!/bin/bash

_opt="-t ${IMAGE_NAME}"

if [ -n "$DOCKERFILE_PATH" ]; then
    _opt="${_opt} -f ${DOCKERFILE_PATH}"
fi

if [ "$DOCKER_TAG" == "next" ]; then
    _opt="${_opt} --build-arg TAG=next"
fi

echo "docker build ${_opt} ."
docker build ${_opt} .
