node {
    def img = "registry.test.eqmh.de/cms-data"
    def oldId = ""
    def id = ""
    def baseImg = "akilli/base"
    def baseId = ""

    stage 'Build'
        checkout scm
        oldId = sh(returnStdout: true, script: "sudo docker inspect --format='{{.Id}}' ${img} || true").trim()
        baseId = sh(returnStdout: true, script: "sudo docker inspect --format='{{.Id}}' ${baseImg} || true").trim()
        sh "sudo docker run --rm -v \$(pwd)/db:/backup -v cms_data:/app -v cms_db:/data ${baseImg} tar cvf /backup/db.tar /app /data"
        sh "sudo docker rmi ${baseId}"
        sh "sudo docker build -t ${img} \$(pwd)/db"
        id = sh(returnStdout: true, script: "sudo docker inspect --format='{{.Id}}' ${img} || true").trim()

    stage 'Registry'
        withCredentials([usernamePassword(credentialsId: 'ci', passwordVariable: 'pass', usernameVariable: 'user')]) {
            sh "sudo docker login -u ${user} -p ${pass} registry.test.eqmh.de"
            sh "sudo docker push ${img}"
        }

    stage 'Live'
        sh "sudo docker-compose -p cms -f docker-compose.yml stop cms-data"
        sh "sudo docker-compose -p cms -f docker-compose.yml rm -f cms-data"
        sh "sudo docker-compose -p cms -f docker-compose.yml up -d --force-recreate"
        sh "sudo docker restart traefik"

    stage 'Clean'
        deleteDir()

        if (oldId && !oldId.equals(id)) {
            sh "sudo docker rmi ${oldId}"
        }
}
