node {
    def img = "registry.test.eqmh.de/cms-data"
    def oldId = ""
    def id = ""
    def baseImg = "akilli/postgres"
    def cont = ""

    stage 'Checkout'
        checkout scm

    stage 'Build'
        oldId = sh(returnStdout: true, script: "sudo docker inspect --format='{{.Id}}' ${img} || true").trim()
        cont = sh(returnStdout: true, script: "sudo docker run -d -v cms_data:/cms-data -v cms_db:/cms-db ${baseImg}").trim()
        sleep 10
        sh "sudo docker exec ${cont} ash -c 'rm -rf /app /data && cp -R /cms-data /app && cp -R /cms-db /data && chown -R app:app /app /data'"
        sh "sudo docker commit ${cont} ${img}"
        sh "sudo docker rm -f ${cont}"
        id = sh(returnStdout: true, script: "sudo docker inspect --format='{{.Id}}' ${img} || true").trim()

    stage 'Registry'
        withCredentials([usernamePassword(credentialsId: 'ci', passwordVariable: 'pass', usernameVariable: 'user')]) {
            sh "sudo docker login -u ${user} -p ${pass} registry.test.eqmh.de"
            sh "sudo docker push ${img}"
        }

    stage 'Live'
        sh "sudo docker-compose -p cms -f docker-compose.yml stop cms-data"
        sh "sudo docker-compose -p cms -f docker-compose.yml rm -f cms-data"
        sh "sudo docker-compose -p cms -f docker-compose.yml up -d --force-recreate"
        sh "sudo docker restart traefik"

    stage 'Clean'
        deleteDir()

        if (oldId && !oldId.equals(id)) {
            sh "sudo docker rmi ${oldId}"
        }
}
