<?php namespace qnd; /** @var callable $§ */?>
<!DOCTYPE html>
<html data-entity="<?= request('entity');?>" data-action="<?= request('action');?>">
    <head>
        <?= §('head');?>
    </head>
    <body>
        <?= §('top');?>
        <?= §('left');?>
        <main>
            <?= §('message');?>
            <?= §('main');?>
        </main>
        <?= §('right');?>
        <?= §('bottom');?>
    </body>
</html>
