<?php namespace qnd; /** @var callable $§ */?>
<!DOCTYPE html>
<html data-id="<?= request('entity');?>-<?= request('action');?>" data-action="<?= request('action');?>" data-entity="<?= request('entity');?>">
    <head>
        <?= §('head');?>
    </head>
    <body>
        <?= §('top');?>
        <?= §('message');?>
        <main>
            <?= §('left');?>
            <?= §('main');?>
            <?= §('right');?>
        </main>
        <?= §('bottom');?>
    </body>
</html>
