<?php
namespace app;
use attr;
/** @var callable $§ */
?>
<section id="<?=$§('id');?>">
    <h1><?=$§('title');?></h1>
    <?php if ($§('data')):?>
        <?php
        $p = $§('params') + ['sort' => null, 'dir' => null];
        if (array_key_exists('page', $p) && $p['page'] <= 1) unset($p['page']);
        ?>
    <table class="data">
        <thead>
            <tr>
                <?php foreach ($§('attr') as $attr):?>
                    <?php $dir = $p['sort'] === $attr['id'] && $p['dir'] === 'asc' ? 'desc' : 'asc'; ?>
                <th>
                    <a href="<?= url('*/*', ['sort' => $attr['id'], 'dir' => $dir] + $p);?>"><?= $attr['name'];?></a>
                    <?php if ($p['sort'] === $attr['id']):?>
                    <span class="icon"><?= $p['dir'] === 'asc' ? 'arrow_drop_up' : 'arrow_drop_down';?></span>
                    <?php endif;?>
                </th>
                <?php endforeach;?>
                <th>
                    <?= i18n('Actions');?>
                </th>
            </tr>
        </thead>
        <tfoot>
            <tr>
                <td colspan="<?= count($§('attr')) + 1 ;?>">
                    <?= §('pager');?>
                </td>
            </tr>
        </tfoot>
        <tbody>
            <?php foreach ($§('data') as $data):?>
            <tr>
                <?php foreach ($§('attr') as $attr):?>
                <td>
                    <?= attr\viewer($data, $attr);?>
                </td>
                <?php endforeach;?>
                <td>
                    <span data-rte="<?= $p['rte'];?>" data-url="<?= asset($data['name']);?>" class="rte icon" title="<?= i18n('Select item');?>">check</span>
                </td>
            </tr>
            <?php endforeach;?>
        </tbody>
    </table>
    <?php else:;?>
    <p><?= i18n('No entries found');?></p>
    <?php endif;?>
</section>
