<?php namespace qnd; /** @var callable $§ */?>
<section id="<?=$§('id');?>">
    <h1><?=$§('title');?></h1>
    <?php if ($§('data')):?>
        <?php
        $p = $§('params') + ['sort' => null, 'dir' => null];
        if (array_key_exists('page', $p) && $p['page'] <= 1) unset($p['page']);
        ?>
    <table class="data">
        <thead>
            <tr>
                <?php foreach ($§('attr') as $attr):?>
                    <?php $dir = $p['sort'] === $attr['id'] && $p['dir'] === 'asc' ? 'desc' : 'asc'; ?>
                <th>
                    <a href="<?= url('*/*', ['sort' => $attr['id'], 'dir' => $dir] + $p);?>"><?= $attr['name'];?></a>
                    <?php if ($p['sort'] === $attr['id']):?>
                    <span class="icon"><?= $p['dir'] === 'asc' ? 'arrow_drop_up' : 'arrow_drop_down';?></span>
                    <?php endif;?>
                </th>
                <?php endforeach;?>
                <th>
                    <?= _('Actions');?>
                </th>
            </tr>
        </thead>
        <tfoot>
            <tr>
                <td colspan="<?= count($§('attr')) + 1 ;?>">
                    <?= section('pager');?>
                </td>
            </tr>
        </tfoot>
        <tbody>
            <?php foreach ($§('data') as $data):?>
            <tr>
                <?php foreach ($§('attr') as $attr):?>
                <td>
                    <?= viewer($attr, $data);?>
                </td>
                <?php endforeach;?>
                <td>
                    <?php if (allowed('*/view')):?>
                    <a href="<?= $data['url'] ?? url('*/view/' . $data['id']);?>" class="icon" title="<?= _('View');?>">visibility</a>
                    <?php endif;?>
                    <?php if (allowed('*/edit') && empty($data['system'])):?>
                    <a href="<?= url('*/edit/' . $data['id']);?>" class="icon" title="<?= _('Edit');?>">edit</a>
                    <?php endif;?>
                    <?php if (allowed('*/delete') && empty($data['system'])):?>
                    <a href="<?= url('*/delete/' . $data['id']);?>" class="delete icon" title="<?= _('Delete');?>">delete</a>
                    <?php endif;?>
                </td>
            </tr>
            <?php endforeach;?>
        </tbody>
    </table>
    <?php else:;?>
    <p><?= _('No entries found');?></p>
    <?php endif;?>
</section>
