<?php namespace qnd; /** @var callable $§ */?>
<section id="<?=$§('§')['id'];?>" class="<?= $§('context');?>">
    <h1><?=$§('title');?></h1>
    <div class="tool">
        <?= section('create');?>
        <?= section('import');?>
        <?= section('search');?>
    </div>
    <?= section('pager');?>
    <?php if ($§('data')):?>
        <?php
        $p = $§('params') + ['sort' => null, 'dir' => null];
        if (array_key_exists('page', $p) && $p['page'] <= 1) unset($p['page']);
        ?>
    <form method="post">
        <fieldset>
            <table>
                <thead>
                    <tr>
                        <?php if (allowed('delete')):?>
                        <th>
                            <input type="checkbox" value="1" title="<?= _('Select all');?>" data-toggle="edit" />
                        </th>
                        <?php endif;?>
                        <?php foreach ($§('attr') as $attr):?>
                            <?php $dir = $p['sort'] === $attr['id'] && $p['dir'] === 'asc' ? 'desc' : 'asc'; ?>
                        <th>
                            <a href="<?= url('*/*', ['sort' => $attr['id'], 'dir' => $dir] + $p);?>"><?= $attr['name'];?></a>
                        </th>
                        <?php endforeach;?>
                        <?php if (allowed('edit') || allowed('view')):?>
                        <th>
                            <?= _('Actions');?>
                        </th>
                        <?php endif;?>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($§('data') as $data):?>
                    <tr>
                        <?php if (allowed('delete')):?>
                        <td>
                            <input id="edit-<?=$data['id'];?>-name" type="checkbox" name="edit[<?=$data['id'];?>]" value="1" data-toggle-id="edit" />
                        </td>
                        <?php endif;?>
                        <?php foreach ($§('attr') as $attr):?>
                            <?php $attr['context'] = $§('context');?>
                        <td>
                            <?=viewer($attr, $data);?>
                        </td>
                        <?php endforeach;?>
                        <?php if (allowed('edit') || allowed('view') || allowed('export')):?>
                        <td>
                            <?php if (allowed('edit')):?>
                            <a href="<?= url('*/edit/' . $data['id']);?>"><?= _('Edit');?></a>
                            <?php endif;?>
                            <?php if (allowed('view')):?>
                            <a href="<?= $data['url'] ?? url('*/view/' . $data['id']);?>"><?= _('View');?></a>
                            <?php endif;?>
                            <?php if (allowed('export')):?>
                            <a href="<?= url('*/export/' . $data['id']);?>"><?= _('Export');?></a>
                            <?php endif;?>
                        </td>
                        <?php endif;?>
                    </tr>
                    <?php endforeach;?>
                </tbody>
            </table>
        </fieldset>
        <?php if (allowed('delete')):?>
        <input type="submit" value="<?= _('Delete');?>" formaction="<?= url('*/delete');?>" />
        <input type="hidden" name="token" value="<?= token();?>" />
        <?php endif;?>
    </form>
    <?php else:;?>
    <p><?= _('No entries found');?></p>
    <?php endif;?>
</section>
