<?php namespace qnd; /** @var callable $§ */?>
<section id="<?=$§('id');?>" class="<?= $§('context');?>">
    <h1><?=$§('title');?></h1>
    <div class="tool">
        <?= section('create');?>
        <?= section('import');?>
        <?= section('search');?>
    </div>
    <?= section('pager');?>
    <?php if ($§('data')):?>
        <?php
        $p = $§('params') + ['sort' => null, 'dir' => null];
        if (array_key_exists('page', $p) && $p['page'] <= 1) unset($p['page']);
        ?>
    <table>
        <thead>
            <tr>
                <?php foreach ($§('attr') as $attr):?>
                    <?php $dir = $p['sort'] === $attr['id'] && $p['dir'] === 'asc' ? 'desc' : 'asc'; ?>
                <th>
                    <a href="<?= url('*/*', ['sort' => $attr['id'], 'dir' => $dir] + $p);?>"><?= $attr['name'];?></a>
                </th>
                <?php endforeach;?>
                <th>
                    <?= _('Actions');?>
                </th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($§('data') as $data):?>
            <tr>
                <?php foreach ($§('attr') as $attr):?>
                    <?php $attr['context'] = $§('context');?>
                <td>
                    <?=viewer($attr, $data);?>
                </td>
                <?php endforeach;?>
                <td>
                    <?php if (allowed('*/edit')):?>
                    <a href="<?= url('*/edit/' . $data['id']);?>"><?= _('Edit');?></a>
                    <?php endif;?>
                    <?php if (allowed('*/delete')):?>
                    <a href="<?= url('*/delete/' . $data['id']);?>" class="delete"><?= _('Delete');?></a>
                    <?php endif;?>
                    <?php if (allowed('*/view')):?>
                    <a href="<?= $data['url'] ?? url('*/view/' . $data['id']);?>"><?= _('View');?></a>
                    <?php endif;?>
                    <?php if (allowed('*/export')):?>
                    <a href="<?= url('*/export/' . $data['id']);?>"><?= _('Export');?></a>
                    <?php endif;?>
                </td>
            </tr>
            <?php endforeach;?>
        </tbody>
    </table>
    <?php else:;?>
    <p><?= _('No entries found');?></p>
    <?php endif;?>
</section>
