<?php namespace qnd; /** @var callable $§ */?>
<?php if ($data = $§('data')):?>
<section id="<?=$§('§')['id'];?>" class="<?= $§('context');?>">
    <h1><?=$§('title');?></h1>
    <form method="post" enctype="multipart/form-data">
        <fieldset>
            <legend><?=$data['name'] ?? _('New Entry');?></legend>
            <?php foreach ($data['_entity']['attr'] as $attr):?>
                <?php $attr['context'] = $§('context');?>
                <?php if (!$html = editor($attr, $data)) continue;?>
            <div data-attr="<?=$attr['id'];?>">
                <?=$html;?>
            </div>
            <?php endforeach;?>
        </fieldset>
        <?php if (allowed('*/admin')):?>
        <a role="button" href="<?= url('*/admin');?>"><?= _('Back');?></a>
        <?php endif;?>
        <input type="submit" value="<?= _('Save');?>" />
        <input type="hidden" name="token" value="<?= token();?>" />
    </form>
</section>
<?php endif;?>
