<?php namespace qnd; /** @var callable $§ */?>
<section id="<?=$§('§')['as'];?>" class="index">
    <h1><?=$§('title');?></h1>
<?php if ($§('data')):?>
    <?= §('search');?>
    <?= §('pager');?>
    <?php foreach ($§('data') as $id => $item):?>
        <?php $eId = $item['_entity']['id'] === 'content' ? $item['entity_id'] : $item['_entity']['id'];?>
    <article>
        <?php foreach ($§('attr') as $attr):?>
            <?php $attr['context'] = $§('context');?>
            <?php if (!$html = viewer($attr, $item)) continue;?>
            <?php if ($attr['id'] === 'name'):?>
                <?php if (allowed($eId . '.view')):?>
        <h1><a href="<?= url($eId . '/view/' . $id);?>"><?=$html;?></a></h1>
                <?php else:?>
        <h1><?=$html;?></h1>
                <?php endif;?>
            <?php else:?>
        <div data-attr="<?=$attr['id'];?>">
            <?=$html;?>
        </div>
            <?php endif;?>
        <?php endforeach;?>
    </article>
        <?php endforeach;?>
<?php else:;?>
    <p><?= _('No entries found');?></p>
<?php endif;?>
</section>
