<?php namespace qnd; /** @var callable $§ */?>
<form id="<?=$§('id');?>"<?php if ($§('action')):?> action="<?= url($§('action'));?>"<?php endif;?> method="post">
    <h1><?= _('Search');?></h1>
    <input type="search" name="param[q]" value="<?=$§('q');?>" placeholder="<?= _('Search Term');?>" />
    <input type="submit" value="search" title="<?= _('Search');?>" class="icon" />
    <input type="hidden" name="token" value="<?= token();?>" />
</form>
