<?php namespace qnd; /** @var callable $§ */?>
<?php if ($data = $§('data')):?>
<article id="<?=$§('§')['id'];?>" class="<?= $§('context');?>">
    <?php foreach ($data['_entity']['attr'] as $attr):?>
        <?php $attr['context'] = $§('context');?>
        <?php if (!$html = viewer($attr, $data)) continue;?>
        <?php if ($attr['id'] === 'name'):?>
    <h1><?=$html;?></h1>
        <?php else:?>
    <div data-attr="<?=$attr['id'];?>">
        <?=$html;?>
    </div>
        <?php endif;?>
    <?php endforeach;?>
</article>
<?php endif;?>
