<?php namespace qnd; /** @var callable $§ */?>
<!doctype html>
<html>
    <head>
        <meta charset="<?= $§('charset');?>" />
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
        <title><?=$§('title');?></title>
        <link rel="stylesheet" href="<?=url_theme('base.css');?>" />
        <link rel="stylesheet" href="<?=url_theme('theme.css');?>" />
    </head>
    <body>
        <header id="header">
            <a href="<?= url();?>"><?= $§('name');?></a>
        </header>
        <?= $§('nav');?>
        <main>
            <?= $§('main');?>
            <aside id="sidebar">
                <?= $§('subnav');?>
            </aside>
        </main>
    </body>
</html>
