<?php namespace qnd; /** @var callable $§ */?>
<!doctype html>
<html>
    <head>
        <meta charset="<?= $§('charset');?>" />
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
        <title><?=$§('title');?></title>
        <link rel="stylesheet" href="<?=url_theme('theme.css');?>" />
    </head>
    <body>
        <header id="header">
            <h1><a href="<?= url();?>"><?= $§('name');?></a></h1>
            <div class="logo">
                <img src="<?= url_theme('akilli-cms.jpg');?>" alt="<?= _('Logo');?>" />
            </div>
        </header>
        <?= $§('nav');?>
        <main>
            <?= $§('main');?>
            <?php if ($§('subnav')):?>
            <aside id="sidebar">
                <?= $§('subnav');?>
            </aside>
            <?php endif;?>
        </main>
    </body>
</html>
