<?php namespace qnd; /** @var callable $§ */?>
<meta charset="<?= config('app', 'charset');?>" />
<?php foreach ($§('meta') as $name => $content):?>
<meta name="<?=$name;?>" content="<?=$content;?>" />
<?php endforeach;?>
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
<title><?=$§('title');?></title>
<link rel="stylesheet" href="<?=url_theme('base.css');?>" />
<link rel="stylesheet" href="<?=url_theme('theme.css');?>" />
<?php if (registered()):?>
<script src="<?=url_lib('ckeditor/ckeditor.js');?>"></script>
<script src="<?=url_theme('theme.js');?>"></script>
<script>
    const app =
    {
        i18n: <?=json_encode(config('i18n'));?>,
        _: function (key)
        {
            return this.i18n[key] ? this.i18n[key] : key;
        }
    };
</script>
<?php endif;?>
