<?php namespace qnd; /** @var callable $§ */?>
<!doctype html>
<html data-path="<?= request('path');?>">
    <head>
        <?= section('head');?>
    </head>
    <body>
        <?= section('top');?>
        <?= section('message');?>
        <main>
            <?= section('left');?>
            <?= section('main');?>
            <?= section('right');?>
        </main>
        <?= section('bottom');?>
    </body>
</html>
