<?php namespace qnd; /** @var callable $§ */?>
<!doctype html>
<html data-path="<?= request('path');?>" data-action="<?= request('action');?>" data-entity="<?= request('entity');?>">
    <head>
        <?= section('head');?>
    </head>
    <body>
        <?= section('top');?>
        <?= section('message');?>
        <main>
            <?= section('left');?>
            <?= section('main');?>
            <?= section('right');?>
        </main>
        <?= section('bottom');?>
    </body>
</html>
