<?php
namespace app;
/** @var callable $§ */
?>
<link rel="stylesheet" href="<?=gui('base.css');?>" />
<link rel="stylesheet" href="<?=gui('style.css');?>" />
<?php if (allowed('account-user')):?>
<script src="<?=gui('ckeditor/ckeditor.js');?>"></script>
<script src="<?=url('app/js');?>"></script>
<script src="<?=gui('admin.js');?>"></script>
<?php endif;?>
<script src="<?=gui('all.js');?>"></script>
