<?php
namespace app;
/** @var callable $var */
?>
<link rel="stylesheet" href="<?=gui('base.css');?>" />
<link rel="stylesheet" href="<?=gui('polyfill/details.css');?>" />
<link rel="stylesheet" href="<?=gui('all.css');?>" />
<link rel="stylesheet" href="<?=gui('admin/admin.css');?>" />
<script src="<?=gui('polyfill/datetime.js');?>"></script>
<script src="<?=gui('app.js');?>"></script>
<script src="<?=gui('admin/delete.js');?>"></script>
<script src="<?=gui('admin/multicheckbox.js');?>"></script>
<script src="<?=gui('admin/priv.js');?>"></script>
<script src="<?=gui('admin/invalid.js');?>"></script>
<script src="<?=gui('toggle.js');?>"></script>
<script src="<?=gui('rte/ckeditor.js');?>"></script>
<script src="<?=gui('rte/rte.js');?>"></script>
<script src="<?=gui('admin/browser.js');?>"></script>
<script src="<?=gui('print.js');?>"></script>
