<?php
namespace app;
?>
<link rel="stylesheet" href="<?php echo gui('base.css'); ?>"/>
<link rel="stylesheet" href="<?php echo gui('editor/editor.css'); ?>"/>
<link rel="stylesheet" href="<?php echo gui('all.css'); ?>"/>
<link rel="stylesheet" href="<?php echo gui('admin.css'); ?>"/>
<script src="<?php echo gui('all.js'); ?>" type="module"></script>
<script src="<?php echo gui('admin.js'); ?>" type="module"></script>
