<?php
namespace app;
?>
<link rel="stylesheet" href="<?php echo guiurl('base.css'); ?>"/>
<link rel="stylesheet" href="<?php echo guiurl('editor/editor.css'); ?>"/>
<link rel="stylesheet" href="<?php echo guiurl('all.css'); ?>"/>
<link rel="stylesheet" href="<?php echo guiurl('admin.css'); ?>"/>
<script src="<?php echo guiurl('all.js'); ?>" type="module"></script>
<script src="<?php echo guiurl('admin.js'); ?>" type="module"></script>
