<?php
namespace app;
use attr;
use session;
/** @var callable $block */
?>
<section id="<?=$block('id');?>" class="form" data-entity="<?=$block('entity')['id'];?>">
    <?php if ($block('title')):?>
    <h1><?=$block('title');?></h1>
    <?php endif;?>
    <form method="post"<?php if ($block('file')):?> enctype="multipart/form-data"<?php endif;?>>
        <fieldset>
            <?php foreach ($block('attr') as $attrId):?>
            <?php if (!($attr = $block('entity')['attr'][$attrId] ?? null)) continue;?>
            <div data-attr="<?=$attr['id'];?>" data-type="<?=$attr['type'];?>">
                <?=attr\frontend($block('data'), $attr);?>
            </div>
            <?php endforeach;?>
        </fieldset>
        <input type="submit" value="<?=i18n('Submit');?>" />
        <input type="hidden" name="token" value="<?=session\token();?>" />
    </form>
</section>
