<?php
namespace app;
use attr;
/** @var callable $var */
?>
<form method="post"<?php if ($var('multipart')):?> enctype="multipart/form-data"<?php endif;?> class="block-form">
    <fieldset>
        <?php foreach ($var('attr') as $attr):?>
        <?=attr\frontend($var('data'), $attr);?>
        <?php endforeach;?>
    </fieldset>
    <div class="action">
        <input type="submit" value="<?=i18n('Submit');?>" />
        <input type="hidden" name="token" value="<?=token();?>" />
    </div>
</form>
