<?php
namespace app;
use attr;
/** @var callable $var */
$app = data('app');
?>
<form method="post"<?php if ($var('multipart')): ?> enctype="multipart/form-data"<?php endif; ?> class="block-form">
    <fieldset>
        <?php foreach ($var('attr') as $attr): ?>
        <?php echo attr\frontend($var('data'), $attr, ['label' => true, 'wrap' => true]); ?>
        <?php endforeach; ?>
    </fieldset>
    <div class="action">
        <?php if ($app['action'] === 'edit' && allowed(id($app['entity_id'], 'index'))): ?>
        <a href="<?php echo actionurl($app['entity_id'], 'index'); ?>" role="button"><?php echo i18n('Back'); ?></a>
        <?php endif; ?>
        <input type="submit" value="<?php echo i18n('Submit'); ?>"/>
        <input type="hidden" name="token" value="<?php echo token(); ?>"/>
    </div>
</form>
