<?php
declare(strict_types=1);
namespace app;
use layout;
$id = data('app', 'id');
$lang = APP['lang'];
?>
<!doctype html>
<html lang="<?php echo $lang; ?>" data-id="<?php echo $id; ?>">
    <head>
        <?php echo layout\render_id('head'); ?>
    </head>
    <body>
        <?php echo layout\render_id('toolbar'); ?>
        <?php echo layout\render_id('header'); ?>
        <?php echo layout\render_id('menu'); ?>
        <?php echo layout\render_id('breadcrumb'); ?>
        <main>
            <app-msg></app-msg>
            <?php echo layout\render_id('content'); ?>
            <?php echo layout\render_id('sidebar'); ?>
        </main>
    </body>
</html>
