<?php
namespace app;
/** @var callable $var */
?>
<meta name="msapplication-config" content="<?=gui('icon/browserconfig.xml');?>"/>
<link rel="manifest" href="<?=gui('icon/manifest.json');?>"/>
<link rel="shortcut icon" href="<?=gui('icon/favicon.ico');?>"/>
<link rel="shortcut icon" href="<?=gui('icon/favicon.png');?>" sizes="32x32"/>
<link rel="shortcut icon" href="<?=gui('cms.svg');?>" sizes="any"/>
<link rel="mask-icon" href="<?=gui('cms.svg');?>"/>
<link rel="apple-touch-icon-precomposed" href="<?=gui('icon/apple-touch.png');?>"/>
