<?php
declare(strict_types=1);
namespace app;
?>
<meta name="msapplication-config" content="<?php echo guiurl('icon/browserconfig.xml'); ?>"/>
<link rel="manifest" href="<?php echo guiurl('icon/manifest.json'); ?>"/>
<link rel="shortcut icon" href="<?php echo guiurl('icon/favicon.ico'); ?>"/>
<link rel="shortcut icon" href="<?php echo guiurl('icon/favicon.png'); ?>" sizes="32x32"/>
<link rel="shortcut icon" href="<?php echo guiurl('cms.svg'); ?>" sizes="any"/>
<link rel="mask-icon" href="<?php echo guiurl('cms.svg'); ?>"/>
<link rel="apple-touch-icon-precomposed" href="<?php echo guiurl('icon/apple-touch.png'); ?>"/>
