<?php
namespace app;
use attr;
/** @var callable $var */
?>
<section class="block-index">
    <?php if ($var('title')):?>
    <h2><?=$var('title');?></h2>
    <?php endif;?>
    <?php if ($var('filter')):?>
    <details>
        <summary><?=i18n('Filter');?></summary>
        <?=$var('filter');?>
    </details>
    <?php endif;?>
    <?=$var('pager-top');?>
    <?php if (!$var('data')):?>
    <p><?=i18n('No entries found');?></p>
    <?php else:?>
    <div class="content">
        <div class="thead">
            <?php foreach ($var('attr') as $attr):?>
                <?php
                $sort = ($attr['id'] === $var('sort') ? '-' : '') . $attr['id'];
                $dir = $var('sort') && $var('sort')[0] === '-' ? 'desc' : 'asc';
                ?>
            <a<?php if ($var('sort') !== false):?> href="<?=query(['sort' => $sort], true);?>"<?php if ($attr['id'] === ltrim($var('sort'), '-')):?> data-sort="<?=$dir;?>"<?php endif;?><?php endif;?>><?=$attr['name'];?></a>
            <?php endforeach;?>
            <span><?=i18n('Actions');?></span>
        </div>
        <?php foreach ($var('data') as $data):?>
            <?php
            $entity = !empty($data['entity_id']) ? cfg('entity', $data['entity_id']) : null;
            $entityId = $entity && $entity['parent_id'] === $data['_entity']['id'] ? $entity['id'] : $data['_entity']['id'];
            $id = ($entity && $entity['parent_id'] === 'block' ? $entity['id'] . '-' : '') . $data['id'];
            $src = $entity && $entity['parent_id'] === 'file' ? $data['url'] : null;
            preg_match('#^file_(audio|iframe|image|video)$#', $entityId, $match);
            ?>
        <article data-id="<?=$id;?>" title="<?=i18n('Select item');?>"<?php if ($src):?> data-src="<?=$src;?>"<?php endif;?><?php if ($match):?> data-type="<?=$match[1];?>"<?php endif;?>>
            <?php foreach ($var('attr') as $attr):?>
            <?=attr\viewer($data, $attr, ['empty' => true, 'h3' => true, 'label' => true, 'wrap' => true]);?>
            <?php endforeach;?>
            <footer>
                <?php if (allowed($entityId . ':view')):?>
                <a href="<?=$data['url'] ?? url($entityId . '/view/' . $data['id']);?>" data-action="view" title="<?=i18n('View');?>"><?=i18n('View');?></a>
                <?php endif;?>
                <?php if (allowed($entityId . ':edit')):?>
                <a href="<?=url($entityId . '/edit/' . $data['id']);?>" data-action="edit" title="<?=i18n('Edit');?>"><?=i18n('Edit');?></a>
                <?php endif;?>
                <?php if (allowed($entityId . ':delete')):?>
                <a href="<?=url($entityId . '/delete/' . $data['id']);?>" data-action="delete" title="<?=i18n('Delete');?>"><?=i18n('Delete');?></a>
                <?php endif;?>
            </footer>
        </article>
        <?php endforeach;?>
    </div>
    <?php endif;?>
    <?=$var('pager-bottom');?>
</section>
