<?php
namespace app;
use attr;
/** @var callable $var */
?>
<section class="block-index">
    <?php if ($var('title') && $var('link')):?>
    <h2><a href="<?=$var('link');?>"><?=$var('title');?></a></h2>
    <?php elseif ($var('title')):?>
    <h2><?=$var('title');?></h2>
    <?php endif;?>
    <?=$var('filter');?>
    <?=$var('pager-top');?>
    <?php if (!$var('data')):?>
    <p><?=i18n('No entries found');?></p>
    <?php else:?>
    <div class="content">
        <?php if ($var('mode') === 'admin'):?>
        <div class="thead">
            <?php foreach ($var('attr') as $attr):?>
                <?php
                $sort = ($attr['id'] === $var('sort') ? '-' : '') . $attr['id'];
                $dir = $var('sort') && $var('sort')[0] === '-' ? 'desc' : 'asc';
                ?>
            <a<?php if ($var('sort') !== false):?> href="<?=url($var('url'), ['sort' => $sort], true);?>"<?php if ($attr['id'] === ltrim($var('sort'), '-')):?> data-sort="<?=$dir;?>"<?php endif;?><?php endif;?>><?=$attr['name'];?></a>
            <?php endforeach;?>
            <span><?=i18n('Actions');?></span>
        </div>
        <?php endif;?>
        <?php foreach ($var('data') as $data):?>
            <?php
            $entity = !empty($data['entity_id']) ? cfg('entity', $data['entity_id']) : null;
            $entityId = $entity && in_array($data['_entity']['id'], [$entity['parent_id'], 'version']) ? $entity['id'] : $data['_entity']['id'];
            $id = $var('mode') === 'browser' ? ($entity && $entity['parent_id'] === 'block' ? $data['entity_id'] . '-' : '') . $data['id'] : null;
            $src = $entity && $entity['parent_id'] === 'file' ? $data['url'] : null;
            $url = $data['url'] ?? url($entityId . '/view/' . $data['id']);
            $link = !$var('mode') && allowed($entityId . '/view') ? $url : null;
            ?>
        <article<?php if ($id):?> data-id="<?=$id;?>"<?php if ($src):?> data-src="<?=$src;?>"<?php endif;?> title="<?=i18n('Select item');?>"<?php endif;?>>
            <?php foreach ($var('attr') as $attr):?>
            <?=attr\wrapper($data, $attr, $attr['id'] === 'name' ? $link : null, true, false, $var('mode') === 'admin');?>
            <?php endforeach;?>
            <?php if ($var('mode') === 'admin'):?>
            <footer>
                <?php if (allowed($entityId . '/view')):?>
                <a href="<?=$data['url'] ?? url($entityId . '/view/' . $data['id']);?>" data-action="view" title="<?=i18n('View');?>"><?=i18n('View');?></a>
                <?php endif;?>
                <?php if (allowed($entityId . '/edit')):?>
                <a href="<?=url($entityId . '/edit/' . $data['id']);?>" data-action="edit" title="<?=i18n('Edit');?>"><?=i18n('Edit');?></a>
                <?php endif;?>
                <?php if (allowed($entityId . '/delete')):?>
                <a href="<?=url($entityId . '/delete/' . $data['id']);?>" data-action="delete" title="<?=i18n('Delete');?>"><?=i18n('Delete');?></a>
                <?php endif;?>
            </footer>
            <?php endif;?>
        </article>
        <?php endforeach;?>
    </div>
    <?php endif;?>
    <?=$var('pager-bottom');?>
</section>
