<?php
namespace app;
use attr;
/** @var callable $§ */
?>
<section id="<?=$§('id');?>" class="index" data-entity="<?=$§('entity')['id'];?>">
    <?php if ($§('title') || $§('create') && allowed($§('entity')['id'] . '/create') || $§('search')):?>
    <header>
        <?php if ($§('title')):?>
        <h1><?=$§('title');?></h1>
        <?php endif;?>
        <?php if ($§('create') && allowed($§('entity')['id'] . '/create')):?>
        <p data-action="create"><a href="<?=url($§('entity')['id'] . '/create');?>"><?=i18n('New Entry');?></a></p>
        <?php endif;?>
        <?=$§('search');?>
    </header>
    <?php endif;?>
<?php if ($§('data')):?>
    <?php if ($§('head')):?>
    <div class="thead">
        <?php foreach ($§('attr') as $aId):?>
            <?php if (!($attr = $§('entity')['attr'][$aId] ?? null)) continue;?>
            <a href="<?=url($§('url'), ['sort' => $attr['id'], 'dir' => $§('sort') === $attr['id'] && $§('dir') === 'asc' ? 'desc' : 'asc'], true);?>"<?php if ($§('sort') === $attr['id']):?> data-sort="<?=$§('dir');?>"<?php endif;?>><?=$attr['name'];?></a>
        <?php endforeach;?>
            <span><?=i18n('Actions');?></span>
    </div>
    <?php endif;?>
    <?php foreach ($§('data') as $data):?>
    <article>
        <?php foreach ($§('attr') as $aId):?>
            <?php if (!($attr = $§('entity')['attr'][$aId] ?? null)) continue;?>
            <?php
            $val = $data[$attr['id']] ?? null;
            $html = attr\viewer($attr, $data);
            ?>
            <?php if (!$§('head') && ($val === null || $val === '' || !$html)) continue;?>
            <?php if ($attr['id'] === 'name'):?>
                <?php if ($§('link') && allowed($§('entity')['id'] . '/view')):?>
        <h2 data-attr="<?=$attr['id'];?>" data-type="<?=$attr['type'];?>">
            <a href="<?=$data['url'] ?? url($§('entity')['id'] . '/view/' . $data['id']);?>"><?=$html;?></a>
        </h2>
                <?php else:?>
        <h2 data-attr="<?=$attr['id'];?>" data-type="<?=$attr['type'];?>"><?=$html;?></h2>
                <?php endif;?>
            <?php elseif (in_array($attr['type'], ['date', 'datetime', 'time'])):?>
        <time data-attr="<?=$attr['id'];?>" data-type="<?=$attr['type'];?>"<?php if ($val !== $html):?> datetime="<?=$val;?>"<?php endif;?>><?=$html;?></time>
            <?php elseif ($attr['id'] === 'aside'):?>
        <aside data-attr="<?=$attr['id'];?>" data-type="<?=$attr['type'];?>">
            <?=$html;?>
        </aside>
            <?php else:?>
        <div data-attr="<?=$attr['id'];?>" data-type="<?=$attr['type'];?>">
            <?=$html;?>
        </div>
            <?php endif;?>
        <?php endforeach;?>
        <?php if ($§('actions')):?>
        <footer>
            <?php if (in_array('view', $§('actions')) && allowed($§('entity')['id'] . '/view')):?>
            <a href="<?=$data['url'] ?? url($§('entity')['id'] . '/view/' . $data['id']);?>" data-action="view"><?=i18n('View');?></a>
            <?php endif;?>
            <?php if (in_array('edit', $§('actions')) && allowed($§('entity')['id'] . '/edit')):?>
            <a href="<?=url($§('entity')['id'] . '/edit/' . $data['id']);?>" data-action="edit"><?=i18n('Edit');?></a>
            <?php endif;?>
            <?php if (in_array('delete', $§('actions')) && allowed($§('entity')['id'] . '/delete')):?>
            <a href="<?=url($§('entity')['id'] . '/delete/' . $data['id']);?>" data-action="delete"><?=i18n('Delete');?></a>
            <?php endif;?>
            <?php if (in_array('select', $§('actions'))):?>
            <span data-id="<?=$data['id'];?>" data-url="<?=$data['name'];?>" data-action="select"><?=i18n('Select item');?></span>
            <?php endif;?>
        </footer>
        <?php endif;?>
    </article>
        <?php endforeach;?>
        <?=$§('pager');?>
<?php else:?>
    <p><?=i18n('No entries found');?></p>
<?php endif;?>
</section>
