<?php
namespace app;
use attr;
/** @var callable $var */
?>
<section class="block-index">
    <?php if ($var('title')): ?>
    <h2><?php echo $var('title'); ?></h2>
    <?php endif; ?>
    <?php if ($var('filter')): ?>
    <details>
        <summary><?php echo i18n('Filter'); ?></summary>
        <?php echo $var('filter'); ?>
    </details>
    <?php endif; ?>
    <?php echo $var('pager-top'); ?>
    <?php if (!$var('data')): ?>
    <p><?php echo i18n('No entries found'); ?></p>
    <?php else: ?>
    <div class="content">
        <div class="thead">
            <?php foreach ($var('attr') as $attr): ?>
                <?php
                $sort = ($attr['id'] === $var('sort') ? '-' : '') . $attr['id'];
                $dir = $var('sort') && $var('sort')[0] === '-' ? 'desc' : 'asc';
                ?>
            <a<?php if ($var('sort') !== false): ?> href="<?php echo urlquery(['sort' => $sort], true); ?>"<?php if ($attr['id'] === ltrim($var('sort'), '-')): ?> data-sort="<?php echo $dir; ?>"<?php endif; ?><?php endif; ?>><?php echo $attr['name']; ?></a>
            <?php endforeach; ?>
            <span><?php echo i18n('Actions'); ?></span>
        </div>
        <?php foreach ($var('data') as $data): ?>
            <?php
            $entity = !empty($data['entity_id']) ? cfg('entity', $data['entity_id']) : null;
            $entityId = $entity && $entity['parent_id'] === $data['_entity']['id'] ? $entity['id'] : $data['_entity']['id'];
            $id = ($entity && $entity['parent_id'] === 'block' ? $entity['id'] . '-' : '') . $data['id'];
            $src = $entity && $entity['parent_id'] === 'file' ? $data['url'] : null;
            ?>
        <article data-id="<?php echo $id; ?>" data-name="<?php echo $data['name']; ?>" title="<?php echo i18n('Select item'); ?>"<?php if ($src): ?> data-src="<?php echo $src; ?>"<?php endif; ?>>
            <?php foreach ($var('attr') as $attr): ?>
            <?php echo attr\viewer($data, $attr, ['empty' => true, 'label' => true, 'subheading' => true, 'wrap' => true]); ?>
            <?php endforeach; ?>
            <footer>
                <?php if (allowed(id($entityId, 'view'))): ?>
                <a href="<?php echo $data['url'] ?? actionurl($entityId, 'view', $data['id']); ?>" data-action="view" title="<?php echo i18n('View'); ?>"><?php echo i18n('View'); ?></a>
                <?php endif; ?>
                <?php if (allowed(id($entityId, 'edit'))): ?>
                <a href="<?php echo actionurl($entityId, 'edit', $data['id']); ?>" data-action="edit" title="<?php echo i18n('Edit'); ?>"><?php echo i18n('Edit'); ?></a>
                <?php endif; ?>
                <?php if (allowed(id($entityId, 'delete'))): ?>
                <a href="<?php echo actionurl($entityId, 'delete', $data['id']); ?>" data-action="delete" title="<?php echo i18n('Delete'); ?>"><?php echo i18n('Delete'); ?></a>
                <?php endif; ?>
            </footer>
        </article>
        <?php endforeach; ?>
    </div>
    <?php endif; ?>
    <?php echo $var('pager-bottom'); ?>
</section>
