<?php
namespace app;
/** @var callable $var */
?>
<nav class="pager">
    <?php if ($var('limits')): ?>
    <div class="limits">
        <?php foreach ($var('limits') as $item): ?>
        <a href="<?php echo $item['url']; ?>"<?php if (!empty($item['current'])): ?> class="current"<?php endif; ?>><?php echo $item['name']; ?></a>
        <?php endforeach; ?>
    </div>
    <?php endif; ?>
    <div class="info">
        <?php echo $var('info'); ?>
    </div>
    <div class="links">
        <?php foreach ($var('links') as $item): ?>
            <?php if (!empty($item['current'])): ?>
        <span><?php echo $item['name']; ?></span>
            <?php else: ?>
        <a href="<?php echo $item['url']; ?>"<?php if ($item['class']): ?> class="<?php echo $item['class']; ?>"<?php endif; ?>><?php echo $item['name']; ?></a>
            <?php endif; ?>
        <?php endforeach; ?>
    </div>
</nav>
