<?php
namespace app;
use request;
/** @var callable $block */
?>
<!doctype html>
<html lang="<?=get('lang');?>" data-action="<?=get('action');?>" data-area="<?=get('area');?>" data-entity="<?=get('entity');?>" data-id="<?=get('id');?>" data-layout="<?=get('layout');?>" data-url="<?=request\get('url');?>" data-parent="<?=get('parent');?>">
    <head>
        <?=block('head');?>
    </head>
    <body>
        <?=block('toolbar');?>
        <?=block('top');?>
        <?=block('msg');?>
        <main>
            <?=block('main');?>
            <?=block('sidebar');?>
        </main>
        <?=block('bottom');?>
    </body>
</html>
