<?php
namespace app;
use request;
/** @var callable $§ */
?>
<!doctype html>
<html lang="<?=get('lang');?>" data-action="<?=get('action');?>" data-area="<?=get('area');?>" data-entity="<?=get('entity');?>" data-id="<?=get('id');?>" data-layout="<?=get('layout');?>" data-url="<?=request\get('url');?>" data-parent="<?=get('parent');?>">
    <head>
        <?=§('head');?>
    </head>
    <body>
        <?=§('top');?>
        <?=§('msg');?>
        <main>
            <?=§('main');?>
            <?=§('sidebar');?>
        </main>
        <?=§('bottom');?>
    </body>
</html>
