<?php
namespace app;
/** @var callable $§ */
?>
<!doctype html>
<html lang="<?=get('lang');?>" data-act="<?=get('act');?>" data-area="<?=get('area');?>" data-ent="<?=get('ent');?>" data-id="<?=get('id');?>" data-layout="<?=get('layout');?>" data-main="<?=get('main');?>" data-parent="<?=get('parent');?>">
    <head>
        <?=§('head');?>
    </head>
    <body>
        <?=§('top');?>
        <?=§('msg');?>
        <main>
            <?=§('main');?>
            <?=§('sidebar');?>
        </main>
        <?=§('bottom');?>
    </body>
</html>
