<?php
namespace app;
use attr;
/** @var callable $§ */
$aside = !empty($§('entity')['attr']['aside']) ? attr\viewer($§('entity')['attr']['aside'], $§('data')) : null;
?>
<article id="<?=$§('id');?>" class="view<?php if ($aside):?> aside<?php endif;?>" data-entity="<?=$§('entity')['id'];?>">
    <?=§('content-top');?>
    <?php foreach ($§('attr') as $attrId):?>
        <?php
        $attr = $§('entity')['attr'][$attrId] ?? null;
        $val = $§('data')[$attrId] ?? null;
        ?>
        <?php if ($attr['id'] === 'aside' || !$attr || $val === null || $val === '' || !($html = attr\viewer($attr, $§('data')))) continue;?>
        <?php if ($attr['id'] === 'name'):?>
    <h1 data-attr="<?=$attr['id'];?>" data-type="<?=$attr['type'];?>"><?=$html;?></h1>
        <?php elseif (in_array($attr['type'], ['date', 'datetime', 'time'])):?>
    <time data-attr="<?=$attr['id'];?>" data-type="<?=$attr['type'];?>"<?php if ($val !== $html):?> datetime="<?=$val;?>"<?php endif;?>><?=$html;?></time>
        <?php else:?>
    <div data-attr="<?=$attr['id'];?>" data-type="<?=$attr['type'];?>">
        <?=$html;?>
    </div>
        <?php endif;?>
    <?php endforeach;?>
    <?=§('content-middle');?>
    <?php if ($aside):?>
    <aside data-attr="aside" data-type="<?=$§('entity')['attr']['aside']['type'];?>">
        <?=$aside;?>
    </aside>
    <?php endif;?>
    <?=§('content-bottom');?>
</article>
