name: release
on:
  workflow_dispatch:
  push:
    branches:
      - master
    tags:
      - "v*.*.*"
    paths-ignore:
      - ".github/**"
      - "**/*.md"
jobs:
  dockerhub:
    uses: akilli/docker/.github/workflows/dockerhub.yml@master
    secrets: inherit
